apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: flux-operator
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: flux
          tailscale.com/tags: "tag:web"
