resources:
  - deploy.yaml
  - netpol.yaml
  - svc.yaml
  - vpa.yaml
  - vmprobe.yaml
  - vmrule.yaml
configMapGenerator:
  - name: blackbox-config
    files:
      - config.yml=blackbox-config/config.yml
