resources:
  - ../../base
namespace: shikanime
patches:
secretGenerator:
  - name: immich-postgres-env
    type: kubernetes.io/basic-auth
    envs:
      - immich-postgres-env/.enc.env
    options:
      disableNameSuffixHash: true
