apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: forgejo
  namespace: monitoring-system
spec:
  groups:
    - name: forgejo
      rules:
        - alert: ForgejoDown
          expr: up{job="forgejo"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Forgejo has been down for 5 minutes
