analytics:
  url: https://api.segment.io/v1/track
  token: null
  user_id: null
appservice:
  id: meta
  address: http://mautrix-meta:29319
  as_token: ENC[AES256_GCM,data:yszjUN7lGrqUJGSg6VkapNEfALBG7yNV1cY8BcqkP+XxwJfS13Qxp8NgeOvLr3LwdsDFJjVdx+TdmeNmT3dwNw==,iv:N6oL+1wpDKO/BLf8Ku4u6Mv2+IVkez25igSBIlE7boI=,tag:3htjxtZ/iiAaG4oqojCauw==,type:str]
  async_transactions: false
  ephemeral_events: true
  hostname: 0.0.0.0
  hs_token: ENC[AES256_GCM,data:WINFi6HkvYXZdB4+iUnWolK3SATwGuLbYq/HaYbtQD7xoMyW3TzaXDxtBAXQ9v+ohXbsQYOa/IKRXQwLyUS73w==,iv:HXPvlwVz/n/lKz+NJixarDT3LvQVfxJyUxCGKKnTSnk=,tag:F6ath/A2/Otx3NanjuVY9A==,type:str]
  port: 29319
  public_address: https://matrix-meta.taila659a.ts.net
  username_template: meta_{{.}}
  bot:
    avatar: mxc://maunium.net/DxpVrwwzPUwaUSazpsjXgcKB
    displayname: Meta bridge bot
    username: metabot
backfill:
  enabled: true
  max_catchup_messages: 500
  max_initial_messages: 50
  queue:
    batch_delay: 20
    batch_size: 100
    enabled: false
    max_batches: -1
    max_batches_override: {}
  threads:
    max_initial_messages: 50
  unread_hours_threshold: 720
bridge:
  async_events: false
  bridge_matrix_leave: false
  bridge_notices: false
  bridge_status_notices: errors
  cleanup_on_logout:
    bad_credentials:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
    enabled: false
    manual:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
  command_prefix: "!meta"
  cross_room_replies: false
  deduplicate_matrix_messages: false
  mute_only_on_create: true
  no_bridge_info_state_key: false
  only_bridge_tags:
    - m.favourite
    - m.lowpriority
  permissions:
    "*": relay
    "@root:matrix.taila659a.ts.net": admin
    matrix.taila659a.ts.net: user
  personal_filtering_spaces: true
  private_chat_portal_meta: true
  relay:
    admin_only: true
    default_relays: []
    displayname_format: "{{ .DisambiguatedName }}"
    enabled: false
    message_formats:
      m.audio:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent an audio file{{ if .Caption
        }}: {{ .Caption }}{{ end }}"
      m.emote: "* <b>{{ .Sender.DisambiguatedName }}</b> {{ .Message }}"
      m.file:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a file{{ if .Caption }}: {{
        .Caption }}{{ end }}"
      m.image:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent an image{{ if .Caption }}:
        {{ .Caption }}{{ end }}"
      m.location:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a location{{ if .Caption
        }}: {{ .Caption }}{{ end }}"
      m.notice: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.text: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.video:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a video{{ if .Caption }}:
        {{ .Caption }}{{ end }}"
  resend_bridge_info: false
  split_portals: false
  tag_only_on_create: true
  unknown_error_auto_reconnect: null
database:
  type: sqlite3-fk-wal
  max_conn_idle_time: null
  max_conn_lifetime: null
  max_idle_conns: 1
  max_open_conns: 5
  uri: file:/data/mautrix-meta.db?_txlock=immediate
direct_media:
  allow_proxy: true
  enabled: false
  media_id_prefix: null
  server_key: ENC[AES256_GCM,data:+c2Lqg7gHc++X5kHzoXqn6Ns+ZqT0PTdDWyCCTZ8KjEhfKqaaON8FPs7fUz1iVxRystLSRL2G0avKw==,iv:UdqrwsuEkI89b15CUE86RI929hniDxOSlUkXtdGMbgs=,tag:kmgluMunbZtxZGoBH9xKGw==,type:str]
  server_name: matrix-discord-media.taila659a.ts.net
  well_known_response: null
double_puppet:
  allow_discovery: false
  secrets:
    matrix.taila659a.ts.net: ENC[AES256_GCM,data:6FLf9kY0kt3UL+xZLRDU5yHoo4M7KpgCuGuoldEZRa6GowYMdRlpdKRFo7nWOSk58TFRfrmAiKTtxp/3bukSFTpyQrqw75MfTA==,iv:YqiG1V6npbSRl4A3A6OjxzsziAsbfxKz8kqVm7PeZ7w=,tag:4H3hyzM7+DIK5BVzyyrMrw==,type:str]
  servers:
    anotherserver.example.org: https://matrix.anotherserver.example.org
encryption:
  allow: true
  allow_key_sharing: true
  appservice: false
  default: true
  delete_keys:
    delete_fully_used_on_decrypt: true
    delete_on_device_delete: true
    delete_outbound_on_ack: false
    delete_outdated_inbound: true
    delete_prev_on_new_session: true
    dont_store_outbound: true
    periodically_delete_expired: true
    ratchet_on_decrypt: true
  msc4190: false
  pickle_key: ENC[AES256_GCM,data:S455z6xeje4QoGGITgcgumRJTG5GFVF2m3zyycPNEWwD6MlYJwUZyUyO80ZDigJTRdKLBTD1bvvGltxc1hduZw==,iv:9rabdGil1PwgddnWfYlr9S+wkWM3xEVy16dR+5j/Rz0=,tag:Eu/EP3yPnhOdRCSVj/5gnQ==,type:str]
  require: false
  rotation:
    disable_device_change_key_rotation: false
    enable_custom: false
    messages: 100
    milliseconds: 6.048e+08
  self_sign: true
  verification_levels:
    receive: cross-signed-tofu
    send: cross-signed-tofu
    share: cross-signed-tofu
homeserver:
  address: https://synapse:8448
  async_media: false
  domain: matrix.taila659a.ts.net
  message_send_checkpoint_endpoint: null
  ping_interval_seconds: 0
  software: standard
  status_endpoint: null
  websocket: false
logging:
  min_level: debug
  writers:
    - type: stdout
      format: pretty-colored
    - type: file
      compress: false
      filename: ./logs/bridge.log
      format: json
      max_backups: 10
      max_size: 100
matrix:
  delivery_receipts: false
  federate_rooms: true
  message_error_notices: true
  message_status_events: false
  sync_direct_chat_list: true
  upload_file_threshold: 5.24288e+06
metrics:
  enabled: ENC[AES256_GCM,data:S5k3bQ==,iv:WqmkP9DdxvmXcvvznMNbjyc3tUwaFA6/XHLR7QFBXjk=,tag:Of0kqKI27uOs3VV7TQdSqg==,type:bool]
  listen_port: ENC[AES256_GCM,data:F9U8FJw=,iv:QiB9pSh7OfdoA7DVG1ZQtu5SEf1G3NZI3i6SHsuLGtg=,tag:WL503rPmunOvqvReJh+SiQ==,type:int]
network:
  allow_messenger_com_on_fb: false
  cache_connection_state: false
  disable_xma_always: false
  disable_xma_backfill: true
  displayname_template: '{{or .DisplayName .Username "Unknown user"}}'
  force_refresh_interval_seconds: 72000
  get_proxy_from: null
  ig_e2ee: false
  min_full_reconnect_interval_seconds: 3600
  mode: null
  proxy: null
  proxy_media: false
  receive_instagram_typing_indicators: true
  send_presence_on_typing: false
provisioning:
  allow_matrix_auth: true
  debug_endpoints: false
  enable_session_transfers: false
  shared_secret: ENC[AES256_GCM,data:OC6zEqjECH8qlXCCSJWxpjApIIxjfLzwOuchcfsRXG8+kLmy6J7P4PYIlIqjUwb4J9Z2tZ5FmI6aCWaQLzpXMw==,iv:NO/7iT3EaQKC4NHqtZ5GFcagnhXPODXxo1t7q8jsAtc=,tag:Yqv3jecZYOEavBeGbXQnqg==,type:str]
public_media:
  enabled: false
  expiry: 0
  hash_length: 32
  signing_key: ENC[AES256_GCM,data:szG5nqDP/zPWhCbwrtqmE8epTgjDRiXYNvV8h+VGuzkpH4MSVxmMKC3GypYGeGCy9AkYH9AjmQvILiT0qdzRtA==,iv:tLl09Yyv+tmJDX9Yp59dvK/8e1uwnqsOBLETo8Qt2TQ=,tag:D8PDdiP5EsH3Yhl0r1fHeA==,type:str]
sops:
  version: 3.13.1
  encrypted_regex: ^(avatar_proxy_key|as_token|hs_token|pickle_key|server_key|shared_secret|signing_key|login_shared_secret_map|secrets|metrics)$
  lastmodified: "2026-07-17T12:16:18Z"
  mac: ENC[AES256_GCM,data:eVqJiBUT6vsdzjlU9QDyKv13RKIHl69dj74E3azL53bjD9v9aB4gSMbvK18IMvefvHPn1nIF+RtL5ulTNU9oqregIDlJ/p75res29Zrk2pjbqYa2ZKMG/QJ+0AFmah9zvr5G7E/cCQFh9tO8Bk5uJQu2vFxcI4qmC5mCjrsZ6VE=,iv:+ugyvf5O6EQx4k5umDfkBM51ZoTjZwjzbrpTDetqNNg=,tag:E23gLh9zUBCEdvm/x0J/cg==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRVZPWDhjKytlRFdZRWg5
        VlIzV3p5dEd1NHN3YVBtM3FKZWV3b1RBZlZBCnNHclkxaXgzM3cxWVlBRU0vUEFu
        WGNQWFJqenZLYVc0cmhDbGJsTFA0d0EKLS0tIHc0STZ2RUV1V1BRbk1WOC9FU0hy
        THVEN1RybjhUdVV0Q3EwbTI2bmFycm8KEXoKxo8WLyNrtZvSyH6WbwmMvxQRhzwT
        +AZOoEOuXoRz5p+DqAJA5Nn15762f2z/6oK2siUfHTmqrmB/ZKFzJA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaHhaNEZhOVJuN2JlQjNr
        Rlc2K2pxLzRvVE9MZUM2NStFWUNjbHp1TW5rCitFSjlmRkdFNmFranExbHRTcEZC
        cVhDUXFJdU16c2gzMHB0dURkam9QSncKLS0tIHFBblpWRERXQkdWTHZHNk13NmFh
        QmJhemhMY254UFpVZ1RYWWlrYlhiNk0KAv0mXW/5guA1HT92r3gj1eGf9UM6iZWG
        RNYwAjVcHW412WLRqQW4uLoDp0RYvdseAPTWZUnmvWZX8AxA9XHwuQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZmtkU3FWU3k3TTNGTUIv
        UzJKUEhqcis0VXNubnVjMmphUUVJVVpyc2hjCjBQSjNMaEhzTWJldDc1bnpDZTU4
        VHZ6cGl5Y3VvLzhGdjRaRGhkRThTL0EKLS0tIExyeVIrMStBaXVYbzhleXFDZTdN
        akhqWXlqTlhBRGIvcGlUalBiUjUwTDgKAxL4eHF63I3gfsmJ8v7QC5dY8BT80tO+
        h8VXXG8eFMpV6dc10fkbiJ6O/PBMYPhHhb8bT2B2S55QpryRd9Y6xg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
