namespace: monitoring-system
secretGenerator:
  - name: alertmanager-config
    options:
      disableNameSuffixHash: true
    files:
      - alertmanager.yaml=alertmanager-config/alertmanager.enc.yaml
