nameReference:
  - version: v1
    kind: Secret
    fieldSpecs:
      - kind: VMAlertmanagerConfig
        group: operator.victoriametrics.com
        path: spec/receivers/discord_configs/webhook_url_secret/name
