resources:
  - httproute.yaml
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: synapse
    newName: matrixdotorg/synapse
    newTag: v1.158.0@sha256:5f868df1f5772907c6dbe973a9b69ab530a5d6bb317c011a3788f7ad78eb1292
