resources:
  - ../../base
  - cert.yaml
  - gateway.yaml
patches:
  - path: patch-pvc.yaml
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - mautrix-twitter.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: twitter
          sectionName: https
    target:
      name: twitter
      kind: HTTPRoute
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - mautrix-twitter.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: twitter
          sectionName: http
    target:
      name: twitter-redirect
      kind: HTTPRoute
