resources:
  - ../../base
  - cert.yaml
  - gateway.yaml
patches:
  - patch: "- op: add\n  path: /spec/hostnames\n  value:\n  - mautrix-twitter.i.shikanime.studio\n- op: add\n  path: /spec/parentRefs\n  value:\n  - name: twitter\n    sectionName: https"
    target:
      name: twitter
      kind: HTTPRoute
  - patch: "- op: add\n  path: /spec/hostnames\n  value:\n  - mautrix-twitter.i.shikanime.studio\n- op: add\n  path: /spec/parentRefs\n  value:\n  - name: twitter\n    sectionName: http"
    target:
      name: twitter-redirect
      kind: HTTPRoute
