resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
  - httproute.yaml
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: oauth2-provider
      app.kubernetes.io/instance: dex
      app.kubernetes.io/name: dex
      app.kubernetes.io/part-of: nishir-platform
      app.kubernetes.io/version: 2.45.0
secretGenerator:
  - name: dex-config
    files:
      - config.yaml=dex/config.enc.yaml
patches:
  - path: patch-netpol.yaml
    target:
      name: dex
      version: v1
      kind: NetworkPolicy
