---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nishir-capacity
allowVolumeExpansion: true
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - wsync
parameters:
  diskSelector: capacity
  fsType: xfs
  nfsOptions: vers=4.0,noresvport
  numberOfReplicas: "1"
  recurringJobSelector: |
    [
      {"name": "default", "isGroup": true},
      {"name": "capacity", "isGroup": true}
    ]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nishir-ephemeral
allowVolumeExpansion: true
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - wsync
parameters:
  diskSelector: nearline
  fsType: xfs
  nfsOptions: vers=4.0,noresvport
  numberOfReplicas: "2"
  recurringJobSelector: |
    [
      {"name": "default", "isGroup": true},
      {"name": "ephemeral", "isGroup": true}
    ]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nishir-transient
allowVolumeExpansion: true
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - wsync
parameters:
  diskSelector: nearline
  fsType: xfs
  nfsOptions: vers=4.0,noresvport
  numberOfReplicas: "2"
  recurringJobSelector: |
    [
      {"name": "default", "isGroup": true},
      {"name": "transient", "isGroup": true}
    ]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nishir-standard
allowVolumeExpansion: true
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - wsync
parameters:
  dataLocality: best-effort
  diskSelector: standard
  fsType: xfs
  nfsOptions: vers=4.0,noresvport
  numberOfReplicas: "2"
  recurringJobSelector: |
    [
      {"name": "default", "isGroup": true},
      {"name": "standard", "isGroup": true}
    ]
