apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      - op: add
        path: /spec/ingress/0/ports
        value:
          - port: https
    target:
      name: synapse
      version: v1
      kind: NetworkPolicy
  - path: patch-sts.yaml
  - path: patch-svc.yaml
