resources:
  - ../nishir
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: machine-learning
      app.kubernetes.io/instance: immich-ml
      app.kubernetes.io/name: immich-ml
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 1.144.1
