resources:
  - ../../base
  - cert.yaml
  - gateway.yaml
patches:
  - patch: "- op: add\n  path: /spec/hostnames\n  value:\n  - mautrix-slack.i.shikanime.studio\n- op: add\n  path: /spec/parentRefs\n  value:\n  - name: slack\n    sectionName: https"
    target:
      name: slack
      kind: HTTPRoute
  - patch: "- op: add\n  path: /spec/hostnames\n  value:\n  - mautrix-slack.i.shikanime.studio\n- op: add\n  path: /spec/parentRefs\n  value:\n  - name: slack\n    sectionName: http"
    target:
      name: slack-redirect
      kind: HTTPRoute
