---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: z-ai
  namespace: shikanime
spec:
  type: AnthropicAPIKey
  targetRefs:
    - name: z-ai
      group: aigateway.envoyproxy.io
      kind: AIServiceBackend
  anthropicAPIKey:
    secretRef:
      name: z-ai-key
      namespace: shikanime
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: z-ai-openai
  namespace: shikanime
spec:
  type: APIKey
  targetRefs:
    - name: z-ai-openai
      group: aigateway.envoyproxy.io
      kind: AIServiceBackend
  apiKey:
    secretRef:
      name: z-ai-key
      namespace: shikanime
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: openrouter
  namespace: shikanime
spec:
  type: APIKey
  targetRefs:
    - name: openrouter
      group: aigateway.envoyproxy.io
      kind: AIServiceBackend
  apiKey:
    secretRef:
      name: openrouter-key
      namespace: shikanime
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: mistral
  namespace: shikanime
spec:
  type: APIKey
  targetRefs:
    - name: mistral
      group: aigateway.envoyproxy.io
      kind: AIServiceBackend
  apiKey:
    secretRef:
      name: mistral-key
      namespace: shikanime
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: nous
  namespace: shikanime
spec:
  type: APIKey
  targetRefs:
    - name: nous
      group: aigateway.envoyproxy.io
      kind: AIServiceBackend
  apiKey:
    secretRef:
      name: nous-key
      namespace: shikanime
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: llama-cpp
  namespace: shikanime
spec:
  type: APIKey
  targetRefs:
    - name: llama-cpp
      group: aigateway.envoyproxy.io
      kind: AIServiceBackend
  apiKey:
    secretRef:
      name: llama-cpp-key
      namespace: shikanime
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: llama-cpp-leader
  namespace: shikanime
spec:
  type: APIKey
  targetRefs:
    - name: llama-cpp-leader
      group: aigateway.envoyproxy.io
      kind: AIServiceBackend
  apiKey:
    secretRef:
      name: llama-cpp-leader-key
      namespace: shikanime
