apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime
resources:
  - ../../base
components:
  - ../../components/tls
patches:
  - path: patch-cert.yaml
    target:
      name: inference-tls
      kind: Certificate
secretGenerator:
  - name: inference-nous
    namespace: shikanime
    envs:
      - inference-nous/.enc.env
  - name: inference-openrouter
    namespace: shikanime
    envs:
      - inference-openrouter/.enc.env
  - name: inference-zai
    namespace: shikanime
    envs:
      - inference-zai/.enc.env
