resources:
  - ../../base
  - cert.yaml
  - gateway.yaml
patches:
  - patch: "- op: add\n  path: /spec/hostnames\n  value:\n  - mautrix-googlechat.i.shikanime.studio\n- op: add\n  path: /spec/parentRefs\n  value:\n  - name: googlechat\n    sectionName: https"
    target:
      name: googlechat
      kind: HTTPRoute
  - patch: "- op: add\n  path: /spec/hostnames\n  value:\n  - mautrix-googlechat.i.shikanime.studio\n- op: add\n  path: /spec/parentRefs\n  value:\n  - name: googlechat\n    sectionName: http"
    target:
      name: googlechat-redirect
      kind: HTTPRoute
