---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: inference-glm-5.3-flash
  namespace: shikanime
spec:
  schema:
    name: OpenAI
  backendRef:
    name: inference
    kind: Backend
    group: gateway.envoyproxy.io
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: zai-key
  namespace: shikanime
spec:
  type: APIKey
  targetRefs:
    - name: zai
      group: aigateway.envoyproxy.io
      kind: AIServiceBackend
  apiKey:
    secretRef:
      name: inference-zai
      namespace: shikanime
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: openrouter-key
  namespace: shikanime
spec:
  type: APIKey
  targetRefs:
    - name: inference-openrouter
      group: aigateway.envoyproxy.io
      kind: AIServiceBackend
  apiKey:
    secretRef:
      name: inference-openrouter
      namespace: shikanime
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: inference
  namespace: shikanime
spec:
  endpoints:
    - fqdn:
        hostname: inference.shikanime.svc.cluster.local
        port: 8080
