resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
namespace: shikanime
configMapGenerator:
  - name: synapse-proxy
    files:
      - synapse-proxy/Caddyfile
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: communication
      app.kubernetes.io/instance: synapse-proxy
      app.kubernetes.io/name: synapse-proxy
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 2.11.2
patches:
  - path: patch-netpol.yaml
    target:
      name: synapse-proxy
      version: v1
      kind: NetworkPolicy
  - path: patch-httproute.yaml
    target:
      name: synapse-proxy
      version: v1
      kind: HTTPRoute
