resources:
  - ../../base
  - cert.yaml
  - gateway.yaml
namespace: shikanime
patches:
  - path: patch-pvc.yaml
  - path: patch-sts.yaml
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - gitea-mirror.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: gitea-mirror
          sectionName: https
    target:
      name: gitea-mirror
      kind: HTTPRoute
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - gitea-mirror.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: gitea-mirror
          sectionName: http
    target:
      name: gitea-mirror-redirect
      kind: HTTPRoute
