resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
namespace: shikanime
patches:
  - target:
      name: twitter
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [mautrix-twitter.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: twitter
            sectionName: https
  - target:
      name: twitter-redirect
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [mautrix-twitter.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: twitter
            sectionName: http
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: communication
      app.kubernetes.io/instance: mautrix-twitter
      app.kubernetes.io/name: mautrix-twitter
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 0.2604.0
secretGenerator:
  - name: mautrix-twitter
    files:
      - config.yaml=matrix-twitter/config.enc.yaml
      - doublepuppet.yaml=matrix-twitter/doublepuppet.enc.yaml
      - registration.yaml=matrix-twitter/registration.enc.yaml
    options:
      disableNameSuffixHash: true
