apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: monitoring-system-grafana-operator
  namespace: monitoring-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: monitoring-system-grafana-operator
  updatePolicy:
    updateMode: InPlaceOrRecreate
