resources:
  - ../../base
  - cert.yaml
namespace: shikanime
components:
  - ../../components/tls
configurations:
  - namereference.yaml
patches:
  - path: patch-pvc.yaml
  - path: patch-sts.yaml
  - path: patch-httproute.yaml
secretGenerator:
  - name: lidarr-env
    envs:
      - lidarr-env/.enc.env
  - name: lidarr-pkcs12-password
    envs:
      - lidarr-pkcs12-password/.enc.env
