resources:
  - ../../base
  - gateway.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - logs.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: victoria-logs
          sectionName: https
    target:
      name: victoria-logs
      kind: HTTPRoute
      namespace: monitoring-system
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - logs.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: victoria-logs
          sectionName: http
    target:
      name: victoria-logs-redirect
      kind: HTTPRoute
      namespace: monitoring-system
  - path: patch-hr.yaml
