apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: jellyfin
  namespace: shikanime
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: jellyfin
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: jellyfin
          tailscale.com/tags: "tag:syncthing"
