apiVersion: v1
kind: Service
metadata:
  name: temporal-postgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app.kubernetes.io/instance: temporal-postgres
    app.kubernetes.io/name: postgres
