resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
namespace: shikanime
configMapGenerator:
  - name: copyparty
    files:
      - ./copyparty/config.conf
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: file-server
      app.kubernetes.io/instance: copyparty
      app.kubernetes.io/name: copyparty
      app.kubernetes.io/part-of: nishir-operation
      app.kubernetes.io/version: 1.20.18
patches:
  - patch: |-
      - op: add
        path: /spec/hostnames/-
        value: copyparty.taila659a.ts.net
      - op: replace
        path: /spec/parentRefs
        value:
          - name: copyparty
            sectionName: http
    target:
      name: copyparty-redirect
      kind: HTTPRoute
  - patch: |-
      - op: add
        path: /spec/hostnames/-
        value: copyparty.taila659a.ts.net
      - op: replace
        path: /spec/parentRefs
        value:
          - name: copyparty
            sectionName: https
    target:
      name: copyparty
      kind: HTTPRoute
