---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: copyparty-ftp-control
spec:
  parentRefs:
    - name: copyparty
      sectionName: ftp-control
  rules:
    - backendRefs:
        - name: ftp
          port: 21
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: copyparty-ftps
spec:
  parentRefs:
    - name: copyparty
      sectionName: ftps
  rules:
    - backendRefs:
        - name: ftp
          port: 990
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: copyparty-sftp
spec:
  parentRefs:
    - name: copyparty
      sectionName: sftp
  rules:
    - backendRefs:
        - name: ftp
          port: 22
