apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "alpine", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" },
      { "name": "qbittorrent", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$",
      "exclude-tags": ["20.04.1", "14.3.9"] } ]'
resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: alpine
    newName: alpine
    newTag: 3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
  - name: qbittorrent
    newName: qbittorrentofficial/qbittorrent-nox
    newTag: 5.2.3-1
