apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - netpol.yaml
  - httproute.yaml
  - udproute.yaml
  - tcproute.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: alpine
    newName: alpine
    newTag: 3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
  - name: qbittorrent
    newName: qbittorrentofficial/qbittorrent-nox
    newTag: 5.2.3-1@sha256:9ebb534fe30bab98622cb84a8c3acecfd88319b2d540f52ecdec7b9f866374d7
  - name: rclone
    newName: rclone/rclone
    newTag: 1.75.0@sha256:b06aed988cf5967de7c25be5925240983981c757f4ed1ac9d2fa659d51d60548
configMapGenerator:
  - name: qbittorrent-rclone
    namespace: shikanime
    files:
      - qbittorrent-rclone/rclone.conf
