---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-syncthing-tls
spec:
  commonName: syncthing
  dnsNames:
    - syncthing
    - syncthing.shikanime
    - syncthing.shikanime.svc.cluster.local
  issuerRef:
    name: nishir
    kind: ClusterIssuer
  secretName: studio-shikanime-i-syncthing-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-syncthing
  namespace: shikanime
spec:
  commonName: syncthing.i.shikanime.studio
  dnsNames:
    - syncthing.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-syncthing
  usages:
    - digital signature
    - key encipherment
    - server auth
