apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: flux-system
spec:
  values:
    vlstorage:
      storageClassName: nishir-standard
      size: 8Gi
    vlinsert:
      ingress:
        enabled: true
        ingressClassName: tailscale
        hosts:
          - name: logs.taila659a.ts.net
            port: http
            path:
              - /insert
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: add
                path: /spec/tls
                value:
                  - hosts:
                      - logs.taila659a.ts.net
            target:
              name: vlogs-vlinsert
              version: v1
              kind: Ingress
