resources:
  - cronjob.yaml
images:
  - name: qbittorrent-cleanup
    newName: ghcr.io/shikanime-labs/xqbit/qbittorrent-cleanup
    newTag: 7b852a7@sha256:7f6e5a6fdc35de5f0eb6c45bf306ae4782a792877e51b633d7a0deb6bb45b04c
