apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lidarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: lidarr
      app.kubernetes.io/name: lidarr
  serviceName: lidarr
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: lidarr
        app.kubernetes.io/name: lidarr
    spec:
      containers:
        - name: lidarr
          image: lidarr
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
          ports:
            - name: http
              containerPort: 8686
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 360
            httpGet:
              path: /ping
              port: http
            timeoutSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /config
            - name: run
              mountPath: /run
          securityContext:
            capabilities:
              add:
                - CHOWN
                - FOWNER
                - SETGID
                - SETUID
            readOnlyRootFilesystem: false
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: S6_READ_ONLY_ROOT
              value: "1"
            - name: TZ
              value: Europe/Paris
            - name: LIDARR__APP__INSTANCENAME
              value: Lidarr
            - name: LIDARR__APP__LAUNCHBROWSER
              value: "False"
            - name: LIDARR__AUTH__APIKEY
              valueFrom:
                secretKeyRef:
                  name: lidarr-env
                  key: apikey
            - name: LIDARR__AUTH__METHOD
              value: Forms
            - name: LIDARR__LOG__LEVEL
              value: info
            - name: LIDARR__LOG__ANALYTICSENABLED
              value: "False"
            - name: LIDARR__SERVER__BINDADDRESS
              value: "*"
            - name: LIDARR__SERVER__PORT
              value: "8686"
            - name: LIDARR__UPDATE__BRANCH
              value: master
            - name: LIDARR__UPDATE__MECHANISM
              value: Docker
      securityContext:
        fsGroup: 1000
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: run
          emptyDir:
            medium: Memory
