apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-longhorn
  namespace: longhorn-system
spec:
  commonName: longhorn.i.shikanime.studio
  dnsNames:
    - longhorn.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-longhorn
  usages:
    - digital signature
    - key encipherment
    - server auth
