resources:
  - ../../base
  - gateway.yaml
namespace: shikanime
components:
  - ../../components/api-server
  - ../../components/a2a
  - ../../components/browser
  - ../../components/dashboard
  - ../../components/honcho
  - ../../components/webhook
patches:
  - path: patch-pvc.yaml
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - automata.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: hermes-agent
          sectionName: https
    target:
      kind: HTTPRoute
      name: hermes-agent-dashboard
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - api.automata.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: hermes-agent
          sectionName: https
    target:
      kind: HTTPRoute
      name: hermes-agent-api-server
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - a2a.automata.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: hermes-agent
          sectionName: https
    target:
      kind: HTTPRoute
      name: hermes-agent-a2a
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - automata.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: hermes-agent
          sectionName: http
    target:
      kind: HTTPRoute
      name: hermes-agent-dashboard-redirect
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - api.automata.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: hermes-agent
          sectionName: http
    target:
      kind: HTTPRoute
      name: hermes-agent-api-server-redirect
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - a2a.automata.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: hermes-agent
          sectionName: http
    target:
      kind: HTTPRoute
      name: hermes-agent-a2a-redirect
secretGenerator:
  - name: hermes-agent
    envs:
      - hermes-agent/.enc.env
  - name: hermes-agent-startup-config
    files:
      - hermes-agent/config.yaml
      - hermes-agent/SOUL.md
  - name: hermes-agent-ssh
    files:
      - id_ed25519=hermes-agent-ssh/id_ed25519.enc
    options:
      disableNameSuffixHash: true
