resources:
  - ../../base
namespace: shikanime
components:
  - ../../components/api
  - ../../components/browser
  - ../../components/dashboard
  - ../../components/webhook
patches:
  - path: patch-pvc.yaml
secretGenerator:
  - name: hermes-agent
    envs:
      - hermes-agent/.enc.env
  - name: hermes-agent-startup-config
    files:
      - hermes-agent/config.yaml
      - hermes-agent/SOUL.md
  - name: hermes-agent-ssh
    files:
      - id_ed25519=hermes-agent-ssh/id_ed25519.enc
    options:
      disableNameSuffixHash: true
