---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-agent-data
spec:
  storageClassName: nishir-standard
  volumeName: hermes-agent-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-agent-profiles-data
spec:
  storageClassName: nishir-standard
  volumeName: hermes-agent-profiles-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-agent-skills-data
spec:
  storageClassName: nishir-standard
  volumeName: hermes-agent-skills-data
