---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-chat
  namespace: shikanime
spec:
  commonName: chat.i.shikanime.studio
  dnsNames:
    - chat.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-chat
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-inference
  namespace: shikanime
spec:
  commonName: inference.i.shikanime.studio
  dnsNames:
    - inference.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-inference
  usages:
    - digital signature
    - key encipherment
    - server auth
