analytics:
  url: https://api.segment.io/v1/track
  token: null
  user_id: null
appservice:
  id: linkedin
  address: http://mautrix-linkedin:29341
  as_token: ENC[AES256_GCM,data:VzZJIfROE04vre1wBXv3J/gNcVA857fekomAmuRFIrt5NltXwOp8ah9DewEJFlDKibzzQ5JwlNKS+Yyc71eYGQ==,iv:Weg/P01MPIt2DtaJCEFh3/quZ+S+E9WeGPAe/Q6bzuY=,tag:Rs+EbplYJV5bCskuljh1ew==,type:str]
  async_transactions: false
  ephemeral_events: true
  hostname: 0.0.0.0
  hs_token: ENC[AES256_GCM,data:ZxBkNG2uXntX/h0bIzv4fMG8c0hcS4OI7rNwwaC8U+5/hP1wCKCgfN4KpDrZXNX37PgpyWbiUFNe3V7WNdmRrQ==,iv:GbAnHS9mwLj7uNVjLlUoSBUqpWDm3KLoZfmiKcsiQ7U=,tag:tKaRUV6nlj0X6ZJBHQQzxQ==,type:str]
  port: 29341
  public_address: https://matrix-linkedin.taila659a.ts.net
  username_template: linkedin_{{.}}
  bot:
    avatar: mxc://maunium.net/CqzBEHjrLsfdqixWZgNHMlRT
    displayname: LinkedIn bridge bot
    username: linkedinbot
backfill:
  enabled: true
  max_catchup_messages: 500
  max_initial_messages: 50
  queue:
    batch_delay: 20
    batch_size: 100
    enabled: false
    max_batches: -1
    max_batches_override: {}
  threads:
    max_initial_messages: 50
  unread_hours_threshold: 720
bridge:
  async_events: false
  bridge_matrix_leave: false
  bridge_notices: false
  bridge_status_notices: errors
  cleanup_on_logout:
    bad_credentials:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
    enabled: false
    manual:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
  command_prefix: "!linkedin"
  cross_room_replies: false
  deduplicate_matrix_messages: false
  kick_matrix_users: true
  mute_only_on_create: true
  no_bridge_info_state_key: false
  only_bridge_tags:
    - m.favourite
    - m.lowpriority
  permissions:
    "*": relay
    "@root:matrix.taila659a.ts.net": admin
    matrix.taila659a.ts.net: user
  personal_filtering_spaces: true
  private_chat_portal_meta: true
  relay:
    admin_only: true
    default_relays: []
    displayname_format: "{{ .DisambiguatedName }}"
    enabled: false
    message_formats:
      m.audio:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent an audio file{{ if .Caption
        }}: {{ .Caption }}{{ end }}"
      m.emote: "* <b>{{ .Sender.DisambiguatedName }}</b> {{ .Message }}"
      m.file:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a file{{ if .Caption }}: {{
        .Caption }}{{ end }}"
      m.image:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent an image{{ if .Caption }}:
        {{ .Caption }}{{ end }}"
      m.location:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a location{{ if .Caption
        }}: {{ .Caption }}{{ end }}"
      m.notice: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.text: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.video:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a video{{ if .Caption }}:
        {{ .Caption }}{{ end }}"
  resend_bridge_info: false
  revert_failed_state_changes: false
  split_portals: false
  tag_only_on_create: true
  unknown_error_auto_reconnect: null
database:
  type: sqlite3-fk-wal
  max_conn_idle_time: null
  max_conn_lifetime: null
  max_idle_conns: 1
  max_open_conns: 5
  uri: file:/data/linkedin.db?_txlock=immediate
direct_media:
  allow_proxy: true
  enabled: false
  media_id_prefix: null
  server_key: ENC[AES256_GCM,data:BWCMsyMVEYnDZrUbDomax5VPJhAjGbtvEiraeVTXMqq+4yhWgEhHJY4+//JmpcOmxH/xnS7bXX/kkA==,iv:R5yPqCJZQbXG1D14nUPs4BwN+XV2PrtNi8qpnook8dg=,tag:CFvTHdKSkhsSKN3N8zGyAw==,type:str]
  server_name: matrix-discord-media.taila659a.ts.net
  well_known_response: null
double_puppet:
  allow_discovery: false
  secrets:
    matrix.taila659a.ts.net: ENC[AES256_GCM,data:EnbJhzsnv/NYfxHS/veCIr/LG6R1SGq+bQjIP8AIFcsBykOxCBdJZvXiEQc/hjkDPggCMgewvujq0ttk5ERSAGlI+Xcfts0bqw==,iv:9zzuSyFRV8dEJiPUpvoTCsc+j60zIBEmbJBnwyFfrG8=,tag:lKtvMCTRtE0iJ13Syc3fFA==,type:str]
  servers:
    anotherserver.example.org: https://matrix.anotherserver.example.org
encryption:
  allow: true
  allow_key_sharing: true
  appservice: false
  default: true
  delete_keys:
    delete_fully_used_on_decrypt: true
    delete_on_device_delete: true
    delete_outbound_on_ack: false
    delete_outdated_inbound: true
    delete_prev_on_new_session: true
    dont_store_outbound: true
    periodically_delete_expired: true
    ratchet_on_decrypt: true
  msc4190: false
  msc4392: false
  pickle_key: ENC[AES256_GCM,data:gqyJgNrJeZcC1WVVgiJ045QRdIZ/F3g/FbxPFqlcKxu0cv7pqgs90O4+rIovlpBYFekMgE3NavaJe3B5acjOyw==,iv:ChUq9h0CPGdLTmKMOHBOj1PH4TcmcA5BbZ5Ku9RkkrE=,tag:+vfcqTHg1h5imxXNEDwjuw==,type:str]
  require: false
  rotation:
    disable_device_change_key_rotation: false
    enable_custom: false
    messages: 100
    milliseconds: 6.048e+08
  self_sign: true
  verification_levels:
    receive: cross-signed-tofu
    send: cross-signed-tofu
    share: cross-signed-tofu
env_config_prefix: null
homeserver:
  address: https://synapse:8448
  async_media: false
  domain: matrix.taila659a.ts.net
  message_send_checkpoint_endpoint: null
  ping_interval_seconds: 0
  software: standard
  status_endpoint: null
  websocket: false
logging:
  min_level: debug
  writers:
    - type: stdout
      format: pretty-colored
    - type: file
      compress: false
      filename: ./logs/bridge.log
      format: json
      max_backups: 10
      max_size: 100
matrix:
  delivery_receipts: false
  federate_rooms: true
  message_error_notices: true
  message_status_events: false
  sync_direct_chat_list: true
  upload_file_threshold: 5.24288e+06
network:
  displayname_template:
    "{{ with .Organization }}{{ . }}{{ else }}{{ .FirstName }} {{ .LastName }}{{
    end }} (LinkedIn)"
  sync:
    create_limit: 10
    update_limit: 0
provisioning:
  allow_matrix_auth: true
  debug_endpoints: false
  enable_session_transfers: false
  shared_secret: ENC[AES256_GCM,data:OfIkCv2FHp/6IZ2/R9ksopjdv/7cTLUgCoSVCZWbAZCL8YnnGmIfUDqD+xz6xME2XNw/gugY8cKRwROZlWH3/w==,iv:KbygrQKhDWJOlanUqxxuDbwAYR0u4kwyXWLS0jhLZuY=,tag:3mAJgIT3l8HAZNw5OyRs9Q==,type:str]
public_media:
  enabled: false
  expiry: 0
  hash_length: 32
  path_prefix: /_mautrix/publicmedia
  signing_key: ENC[AES256_GCM,data:U0Kgse+5Z3+JSPFbryz4lg53TCXuLFC2F2No6ERSEBna6yDquPCc+8PCyHyjXg7Q+5f3NPwwsGAKDaOvkiaXlw==,iv:rCL1efZxjtDhFJ0TMViG/IEnwelbPfChhttIVy6FTWQ=,tag:A2sdqOwiF5cdZWaHqYeXTg==,type:str]
  use_database: false
sops:
  version: 3.13.1
  encrypted_regex: ^(avatar_proxy_key|as_token|hs_token|pickle_key|server_key|shared_secret|signing_key|login_shared_secret_map|secrets)$
  lastmodified: "2026-07-17T14:02:21Z"
  mac: ENC[AES256_GCM,data:E8E31+xxUQswwAoxoeFn+VOiyYGAIcDn62sLMeGQExSi8s2Mbutv9COFSE55ar8T21oCaHvawNUF/nMt+xGPzxRhIPSVRQs75ic5McZ36ark1TfYK3/y/3I25MjM2fl32vdML6q2Hpz5ZIZsW9G7cW8ygH5ELe9tuUMAgdvHb8Y=,iv:T+71N91eHBU1zEKjDV84skql7bTfOk0gE26X8p4QBFA=,tag:f+cq2dswbj1mzDHjsbOBOA==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdHpka2haOUR0cHF5anNM
        WDY2eXFNUnZVazlsd1Z2ZW9BMWZsMW5LbHdBCnY0K1FNRlU4bU9Rd09MeGZGU2Ix
        R1hGeGJBUThuL2dHS29uTGRIVU52S1EKLS0tIFpqRWE2MGdoS2d2cDV1dFRxQWEy
        ZEFVaklOV0UxanhyU3ZhMGxlaWp0Sm8KitC4ljatLWdhbUh7aS7eSQyfq9viYZN3
        Taxu5YMMB2cIY4bh3k1bOPZf9mpKRYywLLPrTudPAu3u1aJGmy65cw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdmRuL0N4Yk1oSWdRMU1s
        azhLbzNXZmVkQTQ1U0hSTnh2YW5vL0RQakRzCjFJYzFxZEhaNEVQN1NmUWZsUHpY
        eldiTzdGMUZkdE1QaW5lb1ZXbDZJcmsKLS0tIG00U0tCcTdheWlOL0pVeDcxTURq
        Y0h4cFFJdVpJdCtlN3hUbEFjWS9ZaTAK/1zIbmEetI7hhw/sLFL4hE6+rEHBc2Vp
        Oz+yRjOqkLKZCEML7+tC8x5hANP5eMRPlWoiZzGEUCgoYgCoqPRiAA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RTB4QlhLWFc0Nm1ZYmNm
        cHVja1JkVHNOelZwTGxLV1pxU2lNL3Q1MFQwCnd0YytxaXBqSndjaUllZEJGNHJl
        WHdGVVpianRqSW9rQVlCYTdsSFlZbDQKLS0tIHhwRUZvaFYzd3FOWXZSdHFvdGlr
        UzkzTWFNaDdUc0psUUxyVjlxNk45WVEK5OchFt7mPzp5D4EvnB6jekUH/+npzrmE
        1D41tF2hJ2oBftNV7cKXxVhoZpktr7FB87s9Ggdxfp+7mIm0bUkTtQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
