apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
  namespace: flux-system
spec:
  chart:
    spec:
      version: 0.11.0
      chart: vertical-pod-autoscaler
      interval: 1h
      sourceRef:
        name: kubernetes-autoscaler
        kind: HelmRepository
        namespace: flux-system
  install:
    crds: Create
  interval: 10m
  releaseName: vpa
  targetNamespace: autoscaler-system
  upgrade:
    crds: CreateReplace
  values:
    admissionController:
      certGen:
        enabled: false
      certManager:
        enabled: true
      podDisruptionBudget:
        maxUnavailable: 1
      replicas: 2
      tls:
        create: false
    recommender:
      podDisruptionBudget:
        maxUnavailable: 1
      replicas: 2
    updater:
      podDisruptionBudget:
        maxUnavailable: 1
      replicas: 2
