---
apiVersion: v1
kind: Service
metadata:
  name: vpa-admission-controller
  namespace: autoscaler-system
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/name: vertical-pod-autoscaler
spec:
  ports:
    - name: metrics
      port: 8944
      targetPort: prometheus
  selector:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/name: vertical-pod-autoscaler
---
apiVersion: v1
kind: Service
metadata:
  name: vpa-recommender
  namespace: autoscaler-system
  labels:
    app.kubernetes.io/component: recommender
    app.kubernetes.io/name: vertical-pod-autoscaler
spec:
  ports:
    - name: metrics
      port: 8942
      targetPort: prometheus
  selector:
    app.kubernetes.io/component: recommender
    app.kubernetes.io/name: vertical-pod-autoscaler
---
apiVersion: v1
kind: Service
metadata:
  name: vpa-updater
  namespace: autoscaler-system
  labels:
    app.kubernetes.io/component: updater
    app.kubernetes.io/name: vertical-pod-autoscaler
spec:
  ports:
    - name: metrics
      port: 8943
      targetPort: prometheus
  selector:
    app.kubernetes.io/component: updater
    app.kubernetes.io/name: vertical-pod-autoscaler
