apiVersion: v1
kind: Service
metadata:
  name: vpa
  namespace: autoscaler-system
  labels:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/name: vertical-pod-autoscaler
spec:
  ports:
    - name: metrics
      port: 8944
      targetPort: prometheus
  selector:
    app.kubernetes.io/component: admission-controller
    app.kubernetes.io/name: vertical-pod-autoscaler
