apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: llama-cpp-head
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "name": "llama-cpp-head",
      "type": "macvlan",
      "master": "br1",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.66.1.16/29"
      }
    }
