---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama-cpp-worker-cache
spec:
  capacity:
    storage: 256Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/cache/llama-cpp
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: feature.node.kubernetes.io/pci-0380_1002.present
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-worker-cache
spec:
  resources:
    requests:
      storage: 256Gi
  volumeName: llama-cpp-worker-cache
  storageClassName: ""
  accessModes:
    - ReadWriteOncePod
