apiVersion: v1
kind: Service
metadata:
  name: mautrix-googlechat
spec:
  sessionAffinity: ClientIP
  ports:
    - name: http
      appProtocol: http
      port: 29320
      targetPort: http
    - name: metrics
      appProtocol: http
      port: 9100
      targetPort: metrics
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: mautrix-googlechat
    app.kubernetes.io/name: mautrix-googlechat
