apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-api-operator
  namespace: flux-system
spec:
  chart:
    spec:
      version: 0.27.0
      chart: cluster-api-operator
      interval: 1h
      sourceRef:
        name: cluster-api-operator
        kind: HelmRepository
  createNamespace: true
  install:
    crds: Create
  interval: 10m
  releaseName: cluster-api-operator
  targetNamespace: capi-operator-system
  upgrade:
    crds: CreateReplace
  values:
    bootstrap:
      rke2:
        version: v0.22.0
    cert-manager:
      enabled: true
    controlPlane:
      rke2:
        version: v0.22.0
    core:
      version: v1.11.5
    enableHelmHook: false
    infrastructure:
      hetzner:
        version: v1.4.2
    leaderElection:
      enabled: true
    replicaCount: 2
