apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cluster-api-crds
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  deletionPolicy: Orphan
  interval: 1h
  path: ./infrastructure/cluster-api/base
  prune: true
  sourceRef:
    name: flux-system
    kind: GitRepository
