apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: victoria-logs
  namespace: monitoring-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: victoria-logs
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: logs
          tailscale.com/tags: "tag:web"
