apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  url: https://registry-1.docker.io/bitnamicharts/external-dns
  interval: 1h
