resources:
  - ../../base
  - backendtlspolicy.yaml
  - cert.yaml
  - gateway.yaml
  - httproutefilter.yaml
namespace: shikanime
components:
  - ../../components/tls
  - ../../components/monitoring
patches:
  - path: patch-sts.yaml
