resources:
  - cluster.yaml
  - hcloud-machine-template.yaml
  - hetzner-cluster.yaml
  - rke2-control-plane.yaml
  - rke2-worker-config-template.yaml
  - machine-deployment.yaml
  - ns.yaml
configurations:
  - config.yaml
