---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmagent-vmks-victoria-metrics-k8s-stack
  namespace: monitoring-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vmagent-vmks-victoria-metrics-k8s-stack
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmalert-vmks-victoria-metrics-k8s-stack
  namespace: monitoring-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vmalert-vmks-victoria-metrics-k8s-stack
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vminsert-vmks-victoria-metrics-k8s-stack
  namespace: monitoring-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vminsert-vmks-victoria-metrics-k8s-stack
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmks-grafana
  namespace: monitoring-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vmks-grafana
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmks-kube-state-metrics
  namespace: monitoring-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vmks-kube-state-metrics
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmks-victoria-metrics-operator
  namespace: monitoring-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vmks-victoria-metrics-operator
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: monitoring-system-grafana-operator
  namespace: monitoring-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: monitoring-system-grafana-operator
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmalertmanager-vmks-victoria-metrics-k8s-stack
  namespace: monitoring-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: vmalertmanager-vmks-victoria-metrics-k8s-stack
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmselect-vmks-victoria-metrics-k8s-stack
  namespace: monitoring-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: vmselect-vmks-victoria-metrics-k8s-stack
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vmstorage-vmks-victoria-metrics-k8s-stack
  namespace: monitoring-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: vmstorage-vmks-victoria-metrics-k8s-stack
  updatePolicy:
    updateMode: Auto
