resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
namespace: shikanime
patches:
  - target:
      name: prowlarr
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [prowlarr.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: prowlarr
            sectionName: https
  - target:
      name: prowlarr-redirect
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [prowlarr.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: prowlarr
            sectionName: http
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: torrent-tracker
      app.kubernetes.io/instance: prowlarr
      app.kubernetes.io/name: prowlarr
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 2.4.0
