apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: llama-cpp-rpc-head
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "name": "llama-cpp-rpc-head",
      "type": "macvlan",
      "master": "br1",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.66.1.2/24"
          }
        ]
      }
    }
