---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nishir-ca
  namespace: cert-manager-trust
spec:
  commonName: cluster.local
  isCA: true
  issuerRef:
    name: nishir-selfsigned
    kind: ClusterIssuer
  secretName: nishir-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-inference
  namespace: shikanime
spec:
  commonName: inference.i.shikanime.studio
  dnsNames:
    - inference.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-inference
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-syncthing
  namespace: shikanime
spec:
  commonName: syncthing.i.shikanime.studio
  dnsNames:
    - syncthing.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-syncthing
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-jellyfin
  namespace: shikanime
spec:
  commonName: jellyfin.i.shikanime.studio
  dnsNames:
    - jellyfin.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-jellyfin
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-qbittorrent
  namespace: shikanime
spec:
  commonName: qbittorrent.i.shikanime.studio
  dnsNames:
    - qbittorrent.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-qbittorrent
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-seerr
  namespace: shikanime
spec:
  commonName: seerr.i.shikanime.studio
  dnsNames:
    - seerr.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-seerr
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-lidarr
  namespace: shikanime
spec:
  commonName: lidarr.i.shikanime.studio
  dnsNames:
    - lidarr.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-lidarr
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-radarr
  namespace: shikanime
spec:
  commonName: radarr.i.shikanime.studio
  dnsNames:
    - radarr.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-radarr
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-sonarr
  namespace: shikanime
spec:
  commonName: sonarr.i.shikanime.studio
  dnsNames:
    - sonarr.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-sonarr
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-whisparr
  namespace: shikanime
spec:
  commonName: whisparr.i.shikanime.studio
  dnsNames:
    - whisparr.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-whisparr
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-matrix
  namespace: shikanime
spec:
  commonName: matrix.i.shikanime.studio
  dnsNames:
    - matrix.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-matrix
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-vaultwarden
  namespace: shikanime
spec:
  commonName: vaultwarden.i.shikanime.studio
  dnsNames:
    - vaultwarden.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-vaultwarden
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-discord
  namespace: shikanime
spec:
  commonName: discord.i.shikanime.studio
  dnsNames:
    - discord.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-discord
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-googlechat
  namespace: shikanime
spec:
  commonName: googlechat.i.shikanime.studio
  dnsNames:
    - googlechat.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-googlechat
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-linkedin
  namespace: shikanime
spec:
  commonName: linkedin.i.shikanime.studio
  dnsNames:
    - linkedin.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-linkedin
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-meta
  namespace: shikanime
spec:
  commonName: meta.i.shikanime.studio
  dnsNames:
    - meta.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-meta
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-signal
  namespace: shikanime
spec:
  commonName: signal.i.shikanime.studio
  dnsNames:
    - signal.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-signal
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-slack
  namespace: shikanime
spec:
  commonName: slack.i.shikanime.studio
  dnsNames:
    - slack.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-slack
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-twitter
  namespace: shikanime
spec:
  commonName: twitter.i.shikanime.studio
  dnsNames:
    - twitter.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-twitter
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-whatsapp
  namespace: shikanime
spec:
  commonName: whatsapp.i.shikanime.studio
  dnsNames:
    - whatsapp.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-whatsapp
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-prowlarr
  namespace: shikanime
spec:
  commonName: prowlarr.i.shikanime.studio
  dnsNames:
    - prowlarr.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-prowlarr
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-bazarr
  namespace: shikanime
spec:
  commonName: bazarr.i.shikanime.studio
  dnsNames:
    - bazarr.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-bazarr
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-copyparty
  namespace: shikanime
spec:
  commonName: copyparty.i.shikanime.studio
  dnsNames:
    - copyparty.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-copyparty
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-dex
  namespace: shikanime
spec:
  commonName: dex.i.shikanime.studio
  dnsNames:
    - dex.i.shikanime.studio
    - accounts.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-dex
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-forgejo
  namespace: shikanime
spec:
  commonName: forgejo.i.shikanime.studio
  dnsNames:
    - forgejo.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-forgejo
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-gitea-mirror
  namespace: shikanime
spec:
  commonName: gitea-mirror.i.shikanime.studio
  dnsNames:
    - gitea-mirror.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-gitea-mirror
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-hermes-agent
  namespace: shikanime
spec:
  commonName: hermes-agent.i.shikanime.studio
  dnsNames:
    - hermes-agent.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-hermes-agent
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-honcho
  namespace: shikanime
spec:
  commonName: honcho.i.shikanime.studio
  dnsNames:
    - honcho.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-honcho
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-immich
  namespace: shikanime
spec:
  commonName: immich.i.shikanime.studio
  dnsNames:
    - immich.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-immich
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-metatube
  namespace: shikanime
spec:
  commonName: metatube.i.shikanime.studio
  dnsNames:
    - metatube.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-metatube
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-automata-dashboard
  namespace: shikanime
spec:
  commonName: dashboard.automata.i.shikanime.studio
  dnsNames:
    - dashboard.automata.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-automata-dashboard
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-lldap
  namespace: shikanime
spec:
  commonName: lldap.i.shikanime.studio
  dnsNames:
    - lldap.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-lldap
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-chat
  namespace: shikanime
spec:
  commonName: chat.i.shikanime.studio
  dnsNames:
    - chat.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-chat
  usages:
    - digital signature
    - key encipherment
    - server auth
