resources:
  - ../../base
  - bundle.yaml
  - ca-rotation-heal.yaml
  - cert.yaml
  - clusterissuer.yaml
secretGenerator:
  - name: cloudflare-api-token
    namespace: cert-manager-trust
    envs:
      - cloudflare-api-token/.enc.env
