resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: forgejo
    newName: codeberg.org/forgejo/forgejo
    newTag: 15.0.6-rootless@sha256:90a7b5b335dd84dbed7f031f2721ae877c713a9226a2b246bc0ed7e1fc7dd9ec
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "forgejo", "tag-regex":
      "^(?P<version>\\d+\\.\\d+\\.\\d+-rootless)$" } ]'
