resources:
  - httproute.yaml
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - tcproute.yaml
  - vpa.yaml
images:
  - name: forgejo
    newName: codeberg.org/forgejo/forgejo
    newTag: 16.0.5-rootless@sha256:5effb7305584aca479b29fde6f9631a6dbe86ae798ae02eeea33a3666f0c0bf8
