apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "lldap", "tag-regex": "^(?P<version>.+)$" } ]'
resources:
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: lldap
    newName: lldap/lldap
    newTag: 2026-08-08-debian@sha256:f2e2d6b34ae063b4e83f700e63857ec1c9a10058ca0792dcb6bafeb1606386e1
