apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: nishir-nearline
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
