apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: lldap
      app.kubernetes.io/name: lldap
  serviceName: lldap
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: lldap
        app.kubernetes.io/name: lldap
    spec:
      containers:
        - name: lldap
          image: lldap
          livenessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: ldap
            timeoutSeconds: 5
          ports:
            - name: ldap
              containerPort: 3890
          readinessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: ldap
            timeoutSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /data
          envFrom:
            - secretRef:
                name: lldap
          securityContext:
            capabilities:
              add:
                - CHOWN
                - FOWNER
                - SETUID
                - SETGID
            readOnlyRootFilesystem: false
      securityContext:
        fsGroup: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lldap-data
