apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: immich
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    name: immich
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    namespace: shikanime
