apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qwen-27b
spec:
  defaultBackend:
    service:
      name: qwen-27b
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - qwen-27b
