resources:
  - aiservicebackend.yaml
  - backend.yaml
  - httproute.yaml
  - sts.yaml
  - svc.yaml
  - vmservicescrape.yaml
  - vmrule.yaml
  - vpa.yaml
images:
  - name: llama-cpp
    newName: ghcr.io/shikanime-labs/machines/llama-cpp
    digest: sha256:eb6bde3e90a11b213f11e7ab793969b6e1ea1dfc6b7501e590644231e90ed3f2
  - name: huggingface
    newName: ghcr.io/shikanime-labs/machines/huggingface
    digest: sha256:68e5c95a2f748d960a7520d5aacd08f920449ba911bb421c51579050e841eed1
configMapGenerator:
  - name: llama-cpp-models-preset
    files:
      - models-preset.ini=llama-cpp-models-preset/models-preset.ini
  - name: llama-cpp-prefetch
    files:
      - entrypoint.sh=llama-cpp-prefetch/entrypoint.sh
