analytics:
  url: https://api.segment.io/v1/track
  token: null
  user_id: null
appservice:
  id: slack
  address: http://mautrix-slack:29335
  as_token: ENC[AES256_GCM,data:1gNxwhN3G71C7N2Q3N3Xl79iq5ADHpFCIqqt7SJSZ97YwPIg9F2ZK942JvauTOaxzM+BiRn0kk95yxImiKjz1g==,iv:vFCWLjzURNf0/JvtHVWeYWC4qKixKLNLlezA+DQsy2Y=,tag:uWfd7lNVvWtQd+2fB/SftQ==,type:str]
  async_transactions: false
  ephemeral_events: true
  hostname: 0.0.0.0
  hs_token: ENC[AES256_GCM,data:y0mRGMpspKzrwJVPVmJX1S5UtycsGGFmROASKG8qNRiaXPTU8n2yCnaKatiw15luKvedVeWmlSEK+fDgq5eRYw==,iv:VJZEIL4LrH6/upAvavyUHM9fvEaWskiPzmdedmFHZhQ=,tag:J9wU7lq2MHFrotI6ViGPTQ==,type:str]
  port: 29335
  public_address: https://matrix-slack-bridge.taila659a.ts.net
  username_template: slack_{{.}}
  bot:
    avatar: mxc://maunium.net/pVtzLmChZejGxLqmXtQjFxem
    displayname: Slack bridge bot
    username: slackbot
backfill:
  enabled: true
  max_catchup_messages: 500
  max_initial_messages: 50
  queue:
    batch_delay: 20
    batch_size: 100
    enabled: false
    max_batches: -1
    max_batches_override: {}
  threads:
    max_initial_messages: 50
  unread_hours_threshold: 720
bridge:
  async_events: false
  bridge_matrix_leave: false
  bridge_notices: false
  bridge_status_notices: errors
  cleanup_on_logout:
    bad_credentials:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
    enabled: false
    manual:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
  command_prefix: "!slack"
  cross_room_replies: false
  deduplicate_matrix_messages: false
  mute_only_on_create: true
  no_bridge_info_state_key: false
  only_bridge_tags:
    - m.favourite
    - m.lowpriority
  permissions:
    "*": relay
    "@root:matrix.taila659a.ts.net": admin
    matrix.taila659a.ts.net: user
  personal_filtering_spaces: true
  private_chat_portal_meta: true
  relay:
    admin_only: true
    default_relays: []
    displayname_format: "{{ .DisambiguatedName }}"
    enabled: false
    message_formats:
      m.audio:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent an audio file{{ if .Caption
        }}: {{ .Caption }}{{ end }}"
      m.emote: "* <b>{{ .Sender.DisambiguatedName }}</b> {{ .Message }}"
      m.file:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a file{{ if .Caption }}: {{
        .Caption }}{{ end }}"
      m.image:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent an image{{ if .Caption }}:
        {{ .Caption }}{{ end }}"
      m.location:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a location{{ if .Caption
        }}: {{ .Caption }}{{ end }}"
      m.notice: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.text: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.video:
        "<b>{{ .Sender.DisambiguatedName }}</b> sent a video{{ if .Caption }}:
        {{ .Caption }}{{ end }}"
  resend_bridge_info: false
  split_portals: false
  tag_only_on_create: true
  unknown_error_auto_reconnect: null
database:
  type: sqlite3-fk-wal
  max_conn_idle_time: null
  max_conn_lifetime: null
  max_idle_conns: 1
  max_open_conns: 5
  uri: file:/data/slack.db?_txlock=immediate
direct_media:
  allow_proxy: true
  enabled: false
  media_id_prefix: null
  server_key: ENC[AES256_GCM,data:HOTeG2zMUnr2wadLJZmNk9zeiHw27HYvu6FniV+6xgFIRYcW9QvFw3Ai1gs9WyNu/V9wSJuXyw8V3g==,iv:Crip9A/NEjdMR+Q+XQrgJe+8dtD/sE7X14operrmNPw=,tag:phogD262WkvMEQLgoJ7RLw==,type:str]
  server_name: matrix-discord-media.taila659a.ts.net
  well_known_response: null
double_puppet:
  allow_discovery: false
  secrets:
    matrix.taila659a.ts.net: ENC[AES256_GCM,data:cEKpZUf3nWUzzSROduRofVXIV7XcAGhl+7rASRBNb+n1BNaXS0vKjSF6ew0+xHYDgGyn3PFYAGtbQOrIk2GKb2LnoPFyHsM3pg==,iv:8j+IyvfyTuyU12LlN8DWHii9tJ7Khb71SA3WcwedXKA=,tag:djO3k11kZWR7r4n9pP5gLg==,type:str]
  servers:
    anotherserver.example.org: https://matrix.anotherserver.example.org
encryption:
  allow: true
  allow_key_sharing: true
  appservice: false
  default: true
  delete_keys:
    delete_fully_used_on_decrypt: true
    delete_on_device_delete: true
    delete_outbound_on_ack: false
    delete_outdated_inbound: true
    delete_prev_on_new_session: true
    dont_store_outbound: true
    periodically_delete_expired: true
    ratchet_on_decrypt: true
  msc4190: false
  pickle_key: ENC[AES256_GCM,data:xkuHFTQ2Z/JWaigSKzF/10YjGTcfp+QsosczPQ2lMTd8EvxiklrPhK23XU5P5KNasAVkaQNyhg7HyxT0BEd8ew==,iv:AbuUpFVYBwX1dXu+4rNCUAYfRwqk+Li87avIHYLr6Bo=,tag:H6Pv+va1BOutqknj7ItqHQ==,type:str]
  require: false
  rotation:
    disable_device_change_key_rotation: false
    enable_custom: false
    messages: 100
    milliseconds: 6.048e+08
  self_sign: true
  verification_levels:
    receive: cross-signed-tofu
    send: cross-signed-tofu
    share: cross-signed-tofu
homeserver:
  address: https://synapse:8448
  async_media: false
  domain: matrix.taila659a.ts.net
  message_send_checkpoint_endpoint: null
  ping_interval_seconds: 0
  software: standard
  status_endpoint: null
  websocket: false
logging:
  min_level: debug
  writers:
    - type: stdout
      format: pretty-colored
    - type: file
      compress: false
      filename: ./logs/bridge.log
      format: json
      max_backups: 10
      max_size: 100
matrix:
  delivery_receipts: false
  federate_rooms: true
  message_error_notices: true
  message_status_events: false
  sync_direct_chat_list: true
  upload_file_threshold: 5.24288e+06
network:
  backfill:
    conversation_count: -1
  channel_name_template:
    "{{if and .IsChannel (not .IsPrivate)}}#{{end}}{{.Name}}{{if .IsNoteToSelf}}
    (you){{end}}"
  custom_emoji_reactions: true
  displayname_template:
    "{{or .Profile.DisplayName .Profile.RealName .Name}}{{if .IsBot}}
    (bot){{end}}"
  mute_channels_by_default: false
  participant_sync_count: 5
  participant_sync_only_on_create: true
  team_name_template: "{{ .Name }}"
  workspace_avatar_in_rooms: false
provisioning:
  allow_matrix_auth: true
  debug_endpoints: false
  enable_session_transfers: false
  shared_secret: ENC[AES256_GCM,data:SmaLxKOqNHuXqUaOj7x7AobZYGVSbwQqLJjqCQxyWlVF8XwvJU87x7mzQaLMl5jrbuhEcryBjJthc0Adzk54sg==,iv:cl+DXClapqeHBpm07yZc6plQP9zepboPhJR9pi1tgCs=,tag:jNr8CdIrvBhhxFUgZAO6HA==,type:str]
public_media:
  enabled: false
  expiry: 0
  hash_length: 32
  signing_key: ENC[AES256_GCM,data:eN0TuYP4Dl/8SVLQiREB6m+CnYOMwmIWZxzwvXjWuhDJt9DIRo91N3O7TwlrkvqyTZWPQZ5gIHDwwo8XBYn77w==,iv:11SKCdMCysDoT2cX7436RiHdsr84ODCC0bg90LJ6QC4=,tag:7h1t7wXdOTCIeytf6OLa9A==,type:str]
sops:
  version: 3.13.1
  encrypted_regex: ^(avatar_proxy_key|as_token|hs_token|pickle_key|server_key|shared_secret|signing_key|login_shared_secret_map|secrets)$
  lastmodified: "2026-07-17T14:02:21Z"
  mac: ENC[AES256_GCM,data:VnukCOoRgLarJOY72Wp55zgEX5GZNENBo6yQyaEnN3h2hmpb0j+SjdDiVVWnVova+u4LrfHDEst1tAab6gtQ91jVdA7+EFerEoKAzhCt3XsbFY/dmX5bMhNlHIjHVT0mZGQH3bComGDHfKXIxmC81HQOd/FNCnTrrD1gxkNfRmc=,iv:eexfzuP4UAnu4dF535UcK95JZMWAelUAf6rBxCbXAmk=,tag:yfcRFd5cXr09EBL7PgYe/A==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM2QwOTlSRE5SUnBxV3FK
        bGduUkF6c0pVQytaZm1EdDVGWklHaUNYZUNBCjU1bVVWNWs2RFdnQW9ZMk1MOThV
        dTRkWG9Fa25VYjFRR3ZkcTh1S29ta00KLS0tIEFaQjM0R3VBYTQ2YXdWc2hPbU1M
        VXQwMEJaRGJjamNVMk5vb0FMN1BhdHcKG5/SRakp9N+HctPjeGkelKLgmNiT8CFf
        m6Oi/JEBcYpWAaHYvZkU11fuJajuFT2ZcRiPaLdflfVtTe2gbHhLNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFam5EcmhwbkVIV0dlbFhM
        VVhTdjBrY2wzOG8wL2x5bGU0NEs4SjRxWUIwCjA2MGFUWC93NG43Znd0c3c3cmVh
        ajRTa09vMXljUnlHL2E2OVNSMGh2UmcKLS0tIE14QTlLOVVXMFNhaG10b2NaSlVM
        NjFsQTVrRWtJaUNyekxZRmJicjh5cXMKpahPe5ixrUWZ4zuYNmeBWJLnDn7pvmtV
        RR2QX4wzvwJDUd39PRjDTrdfWEXnx4KLLr3T7D3ba9hoXQVUTxpIEQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMEJrUHg1Nk04UU14TlJl
        Wno4V1BBaURqQjlwWktMNENlaGFiR0dWa2tFCmNpdlBxVkVDdDBvQUlzNnZjdmNo
        T2kxZURvcEo2THBvK1AwaC9GMk9LalUKLS0tIHdNTUFLcWlMVmR2dDV1TkgyemhI
        YmVZbnJRQ1cxb1JpMXAvZ2xCRlQycVUKc1DTxTTn8RzKGGuVIrvsNcADb54g9ZY8
        vVMyt/BXE4nf3Sjycc3nyP+H+rikmXZ88DNdY0FMzZaOeSIrZr54xA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
