analytics:
  url: https://api.segment.io/v1/track
  token: null
  user_id: null
appservice:
  id: slack
  address: http://mautrix-slack.shikanime.svc.cluster.local:29335
  as_token: ENC[AES256_GCM,data:v+gzesPtzQVHJdZVbdQrjSrkjPeYGGvjK2CeWC20TOOjKjlxqmmg2d2QS6t5/o1/pgCRZtqIa/9a/Qq3631CYA==,iv:5nbccy70XNxRkLVFHjDHdoBAk0bgzUl4B6WH3iebVgM=,tag:CmHkry5X9dcagDJ3qJ/Umw==,type:str]
  async_transactions: false
  ephemeral_events: true
  hostname: 0.0.0.0
  hs_token: ENC[AES256_GCM,data:qgpVQSq0p/VuNoXoViRXrHBGiQ6Rhr/4pj6gUdhrHMwegwTp3Y9pa/tIKrZ6iphu9loJ4QHtuazNTi7pmgr4xw==,iv:g0baAc6N8EprZRlMteSqTDMfUK0TyK9fyW+BTfdcy+Q=,tag:Tdeh7xyiZwoXTU0Bn2PUmQ==,type:str]
  port: 29335
  public_address: https://matrix-slack-bridge.taila659a.ts.net
  username_template: slack_{{.}}
  bot:
    avatar: mxc://maunium.net/pVtzLmChZejGxLqmXtQjFxem
    displayname: Slack bridge bot
    username: slackbot
backfill:
  enabled: true
  max_catchup_messages: 500
  max_initial_messages: 50
  queue:
    batch_delay: 20
    batch_size: 100
    enabled: false
    max_batches: -1
    max_batches_override: {}
  threads:
    max_initial_messages: 50
  unread_hours_threshold: 720
bridge:
  async_events: false
  bridge_matrix_leave: false
  bridge_notices: false
  bridge_status_notices: errors
  cleanup_on_logout:
    bad_credentials:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
    enabled: false
    manual:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
  command_prefix: "!slack"
  cross_room_replies: false
  deduplicate_matrix_messages: false
  mute_only_on_create: true
  no_bridge_info_state_key: false
  only_bridge_tags:
    - m.favourite
    - m.lowpriority
  permissions:
    "*": relay
    "@root:matrix.i.shikanime.studio": admin
    matrix.i.shikanime.studio: user
  personal_filtering_spaces: true
  private_chat_portal_meta: true
  relay:
    admin_only: true
    default_relays: []
    displayname_format: "{{ .DisambiguatedName }}"
    enabled: false
    message_formats:
      m.audio: "<b>{{ .Sender.DisambiguatedName }}</b> sent an audio file{{ if .Caption }}: {{ .Caption }}{{ end }}"
      m.emote: "* <b>{{ .Sender.DisambiguatedName }}</b> {{ .Message }}"
      m.file: "<b>{{ .Sender.DisambiguatedName }}</b> sent a file{{ if .Caption }}: {{ .Caption }}{{ end }}"
      m.image: "<b>{{ .Sender.DisambiguatedName }}</b> sent an image{{ if .Caption }}: {{ .Caption }}{{ end }}"
      m.location: "<b>{{ .Sender.DisambiguatedName }}</b> sent a location{{ if .Caption }}: {{ .Caption }}{{ end }}"
      m.notice: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.text: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.video: "<b>{{ .Sender.DisambiguatedName }}</b> sent a video{{ if .Caption }}: {{ .Caption }}{{ end }}"
  resend_bridge_info: false
  split_portals: false
  tag_only_on_create: true
  unknown_error_auto_reconnect: null
database:
  type: sqlite3-fk-wal
  max_conn_idle_time: null
  max_conn_lifetime: null
  max_idle_conns: 1
  max_open_conns: 5
  uri: file:/data/slack.db?_txlock=immediate
direct_media:
  allow_proxy: true
  enabled: false
  media_id_prefix: null
  server_key: ENC[AES256_GCM,data:vjEYYdcJkVORosvlPH9nSYRIX4JSr0J8N5par9K8JqQxuoa/ZeGI4/8Hk2eGjOBrkONvZSQr7a1H2w==,iv:MwqHHrKzlPlCmZJ1HZtYatRMPwxmTWbR4RwAJSNR3ck=,tag:9iM1h2eeyKSnG+vZR1gaLQ==,type:str]
  server_name: matrix-discord-media.taila659a.ts.net
  well_known_response: null
double_puppet:
  allow_discovery: false
  secrets:
    matrix.i.shikanime.studio: ENC[AES256_GCM,data:r1Tw6K/uEVsWBPw8PXJXtoJVfjI5ZoKA6UDSy68iRA+M9CLmlwdtAM5Gs0BnwK0kdzVs6pUNymTaUy65WdceeW7tRoFknASK4Q==,iv:4p0Spi3uuJxecLFC7NRIug2br2/F6JKwuqzs6bFMuAs=,tag:Pviz7UdVt3Ac1ieiHqlQHA==,type:str]
  servers:
    anotherserver.example.org: https://matrix.anotherserver.example.org
encryption:
  allow: true
  allow_key_sharing: true
  appservice: false
  default: true
  delete_keys:
    delete_fully_used_on_decrypt: true
    delete_on_device_delete: true
    delete_outbound_on_ack: false
    delete_outdated_inbound: true
    delete_prev_on_new_session: true
    dont_store_outbound: true
    periodically_delete_expired: true
    ratchet_on_decrypt: true
  msc4190: false
  pickle_key: ENC[AES256_GCM,data:6My3DKXviZE5zoq7hRc/16T7kOxayXADBU3UFHKurHddPb0XQLtkWnsJsKg6a2RQx7u4ZZaU0IanoN1TS88QLg==,iv:t7VqMH8lqZblNFqi8q/GHvK2v0n+gMZqJPh4dJt6MlI=,tag:C0qEGRWF0umgsHffQIwT4A==,type:str]
  require: false
  rotation:
    disable_device_change_key_rotation: false
    enable_custom: false
    messages: 100
    milliseconds: 6.048e+08
  self_sign: true
  verification_levels:
    receive: cross-signed-tofu
    send: cross-signed-tofu
    share: cross-signed-tofu
homeserver:
  address: https://synapse.shikanime.svc.cluster.local:8448
  async_media: false
  domain: matrix.i.shikanime.studio
  message_send_checkpoint_endpoint: null
  ping_interval_seconds: 0
  software: standard
  status_endpoint: null
  websocket: false
logging:
  min_level: debug
  writers:
    - type: stdout
      format: pretty-colored
    - type: file
      compress: false
      filename: ./logs/bridge.log
      format: json
      max_backups: 10
      max_size: 100
matrix:
  delivery_receipts: false
  federate_rooms: true
  message_error_notices: true
  message_status_events: false
  sync_direct_chat_list: true
  upload_file_threshold: 5.24288e+06
network:
  backfill:
    conversation_count: -1
  channel_name_template: "{{if and .IsChannel (not .IsPrivate)}}#{{end}}{{.Name}}{{if .IsNoteToSelf}} (you){{end}}"
  custom_emoji_reactions: true
  displayname_template: "{{or .Profile.DisplayName .Profile.RealName .Name}}{{if .IsBot}} (bot){{end}}"
  mute_channels_by_default: false
  participant_sync_count: 5
  participant_sync_only_on_create: true
  team_name_template: "{{ .Name }}"
  workspace_avatar_in_rooms: false
provisioning:
  allow_matrix_auth: true
  debug_endpoints: false
  enable_session_transfers: false
  shared_secret: ENC[AES256_GCM,data:Wgg8vZm4k/lv+XFF0E5YX3HbkKT3pUAQKd5++pypAaEzlh2SoXKjMWbdeakPFISbS/YuHXc0D/bGRmQgDEZaYA==,iv:zfqIEzugo6vKINy0a4i1wuetoG6J70pca22Enuv689g=,tag:LXbnUAwgCNU3POyjyG8hiQ==,type:str]
public_media:
  enabled: false
  expiry: 0
  hash_length: 32
  signing_key: ENC[AES256_GCM,data:1qE9SbJIkRR/RIm8lEo3GdJDvQxGw33l4aJVcYu9t5UDNmqohbOLdcKuGxgQO5ZwY3Fn9ks/xEgrnjbeBL2oFQ==,iv:1b91Dd+Tn2BHu6aiZgjrU6GEmRUn2wryaAqmBpEe5z8=,tag:Pxzlue+xuITlfsiqGiq2Ew==,type:str]
sops:
  version: 3.13.3
  encrypted_regex: ^(avatar_proxy_key|as_token|hs_token|pickle_key|server_key|shared_secret|signing_key|login_shared_secret_map|secrets)$
  lastmodified: "2026-08-31T12:15:06Z"
  mac: ENC[AES256_GCM,data:ccKXLcLe20+/EuXhKmo9CQGaSBAUOW7TJLe4jbgFlXU8/asA21JAy+Y8FJOqdJL3Yhy8oGmwllDhb0PyMZ5Qks3hAezxekziuuPk4T/xjdCKXWbxrixYPB6KldMRdMvXxsRosJaGe/pTeBexSzCzYBqETv2TvKNMWGkNwWmTBik=,iv:IBzw/+p/b0suZEHcN/GiCdgDJreig96PJXpUpvWTnis=,tag:uNTOSQOvhMsYw26NdfV8Rw==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbFgxR2N4aUYyVG1jUm0z
        SUtOMENQUy83MStaVkdpd1VZY2ZNdmVTV0JnCmVSOTZETnJTRXpwdjFNNmd2Smlv
        TUp1c3Buc0E2eFU4VEs2aitBRlcvZzAKLS0tIGJIZ3Q1SnhraHF3NUhMVG5CTmpH
        alZWTnQvUzNkQU9wYlB2YzZCUEZ4dzgKtf7g7OqvNed4qAfg7/Shv5BV6tTMBKTT
        qUtdOoInvyy1+tV7WtdhnNtiDukfUuhr0Ve61+dIFwEykgY5bwM6LA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeTZLTVV4d0J3L3hSM2d2
        WEYxQjBIQlBVYXRHcEtNS3I2RGdscTlmenlZCkFkUDJCeTJ0U0wrcVZTYlQwUHpM
        VFY4OUo2c1RHWWQvOVczQjBQaU1LWGsKLS0tIHd4czA5cHdjUzc4WUtkQUFrbEF3
        VDdvSW04TzNCdVVHNVBOUWVXNDhFdVEKuWQKgQzx/GonPtPr7HxM+8AVSPtLeleN
        DiV0p0cE2nP12gX0+7D8D2KBDfAgJG9581G703u2kByy1vIApKW3HQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MlNNeW9GL09vMXhEdXhn
        ZHJuTzBNMUgxUHZVcmtXb1pINW44aXRMY1hrCkVTdEovWGJaTEhrM0FFUkpPR3BI
        TDVHRUZhdlFBTHA0TWsvV09URzc0NzQKLS0tIDJSaHlhNllETktlN2paYjhsdDJr
        dTVlWm51cFhMYVMySDc0a1Q1MEZDU2MKBnpQ/PdJNo3wuPzaSa8Qqe9BNpW6J/PW
        8x7XTdHwby2DxXIF/7lTZmNT3b2AhOwFWEIScFVtfm6eU+3CjVO0Yw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
