---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: longhorn-driver-deployer
  namespace: longhorn-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: longhorn-driver-deployer
  updatePolicy:
    updateMode: InPlaceOrRecreate
  resourcePolicy:
    containerPolicies:
      - containerName: longhorn-driver-deployer
        maxAllowed:
          memory: 1Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: longhorn-ui
  updatePolicy:
    updateMode: InPlaceOrRecreate
  resourcePolicy:
    containerPolicies:
      - containerName: longhorn-ui
        maxAllowed:
          memory: 1Gi
