resources:
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: valkey
    newName: valkey/valkey
    newTag: 9-alpine@sha256:48332870af354a799964c0012ae1194a0bf2bf894eb508f945810596dc2d8d11
