apiVersion: v1
kind: Service
metadata:
  name: immich-valkey
spec:
  ports:
    - name: valkey
      port: 6379
      targetPort: valkey
  selector:
    app.kubernetes.io/instance: immich-valkey
    app.kubernetes.io/name: valkey
