resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: bazarr
    newName: lscr.io/linuxserver/bazarr
    newTag: 1.5.6
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "bazarr", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" }
      ]'
