resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: bazarr
    newName: lscr.io/linuxserver/bazarr
    newTag: 1.6.0@sha256:b3d44d324399152be4d50775ff639a364c0fa1cfda67f71b1f38264c4d0ca09f
  - name: rclone
    newName: rclone/rclone
    newTag: 1.75.0@sha256:b06aed988cf5967de7c25be5925240983981c757f4ed1ac9d2fa659d51d60548
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "bazarr", "tag-regex": "^(?P<version>\\d+\\.\\d+\\.\\d+)$" }
      ]'
configMapGenerator:
  - name: bazarr-rclone
    namespace: shikanime
    files:
      - rclone/rclone.conf
