resources:
  - ../../base
namespace: shikanime
components:
  - ../../components/ldap
  - ../../components/gpu
patches:
  - path: patch-pvc.yaml
  - path: patch-sts.yaml
secretGenerator:
  - name: jellyfin-ldap
    files:
      - LDAP-Auth.xml=jellyfin/LDAP-Auth.enc.xml
