resources:
  - ../../base
  - backendtlspolicy.yaml
  - cert.yaml
  - gateway.yaml
namespace: shikanime
components:
  - ../../components/tls
  - ../../components/ldap
  - ../../components/gpu
configurations:
  - namereference.yaml
patches:
  - path: patch-sts.yaml
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - jellyfin.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: jellyfin
          sectionName: http
    target:
      name: jellyfin
      kind: HTTPRoute
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - jellyfin.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: jellyfin
          sectionName: http
    target:
      name: jellyfin-redirect
      kind: HTTPRoute
secretGenerator:
  - name: jellyfin-pkcs12-password
    envs:
      - jellyfin-env/.enc.env
  - name: jellyfin-ldap
    files:
      - LDAP-Auth.xml=jellyfin-ldap/LDAP-Auth.enc.xml
  - name: jellyfin
    files:
      - encoding.xml=jellyfin/encoding.enc.xml
      - network.xml=jellyfin/network.enc.xml
