apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
spec:
  template:
    spec:
      initContainers:
        - name: startup-config-sync
          image: rclone
          args:
            - copy
            - --copy-links
            - /mnt/startup-config/
            - /mnt/config/config/
          command:
            - rclone
          volumeMounts:
            - name: config
              mountPath: /mnt/config
            - name: startup-config
              mountPath: /mnt/startup-config
              readOnly: true
          securityContext:
            capabilities:
              add:
                - FOWNER
      volumes:
        - name: startup-config
          secret:
            secretName: jellyfin-startup
