apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery-system
spec:
  podMetricsEndpoints:
    - interval: 60s
      path: /metrics
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: node-feature-discovery
    matchExpressions:
      - key: role
        operator: In
        values:
          - master
          - gc
          - worker
