connectors:
  - name: LDAP
    type: ldap
    id: ldap
    config:
      bindDN: uid=admin,ou=people,dc=shikanime,dc=studio
      bindPW: ENC[AES256_GCM,data:8Y0j9qI3jRhxo6yfiJpKPZF3hDEG03/+kL2c1A==,iv:N0Qut8tU9GzQK8mWX4WbMHo1/BiYqpfuRd1fI+njdHA=,tag:kt4/Ji8WXo+c0SGS0rr9Zw==,type:str]
      groupSearch:
        baseDN: ou=groups,dc=shikanime,dc=studio
        filter: (objectClass=groupOfUniqueNames)
        nameAttr: cn
        userMatchers:
          - groupAttr: member
            userAttr: DN
      host: lldap.shikanime.svc.cluster.local:6360
      insecureNoSSL: false
      insecureSkipVerify: true
      userSearch:
        baseDN: ou=people,dc=shikanime,dc=studio
        emailAttr: mail
        idAttr: uid
        nameAttr: displayName
        preferredUsernameAttr: uid
        username: uid
issuer: https://accounts.taila659a.ts.net
oauth2:
  skipApprovalScreen: true
staticClients:
  - name: Forgejo
    id: forgejo
    secret: ENC[AES256_GCM,data:hkRzehjNjiJEGzxd6E5O5nRnJoUNnDJO78Yq7xRqhhP+5DKHFdy9NBNv6XrBBqhePl0ejCc+26P1qlC/UQ5Cow==,iv:A3ErAHiZP+fmSV+yqWAjCPCbqHqzOkHEfwUQ+YazTvU=,tag:tKfzPayoweVi0pLcMnPDLw==,type:str]
    redirectURIs:
      - https://forgejo.taila659a.ts.net/user/oauth2/Dex/callback
    trustedPeers:
      - "*"
  - name: Gitea Mirror
    id: gitea-mirror
    secret: ENC[AES256_GCM,data:MsOuyUBEa2+hSbAVXO2oSQthJibriBSLQ2OarlDrdN0a4lzw8lPd+ta6eDhu0vKb4zglBRv3xV7HBg3IfL1Gng==,iv:k4fBXnGzR6oSwGYcYeFPDw5XtlomEIzxjte29HeLUoo=,tag:k/MPCP9twYASZtsdOiBesQ==,type:str]
    redirectURIs:
      - https://gitea-mirror.taila659a.ts.net/api/auth/sso/callback/dex
    trustedPeers:
      - "*"
  - name: Synapse
    id: synapse
    secret: ENC[AES256_GCM,data:ZPzLtMH3a7tppafZ2JiqAweDYUCmvjgWFBd0lxDTjAxQ06VkHM6btQq0jnUzMSwFIuAi9p9YNcviv9bPXvw6Dg==,iv:KHKgt828saa1DZifKyOxtaIEnLI3Naq/3ox1L9mi/9g=,tag:RfX6ZCVYt5IfDaAzx3OfjQ==,type:str]
    redirectURIs:
      - https://matrix.taila659a.ts.net/_matrix/oidc/callback/synapse
    trustedPeers:
      - "*"
  - name: Hermes Agent Dashboard
    id: hermes-agent
    public: true
    secret: ""
    redirectURIs:
      - https://automata-dashboard.taila659a.ts.net/auth/callback
    trustedPeers:
      - "*"
  - name: Vaultwarden
    id: vaultwarden
    secret: ENC[AES256_GCM,data:wqukuoC9SsBL3P2OVD+7b38PsKvigJv0OpcK6M7R0urP5CFfNhx6dUsJNA9ynxuiK7PozWKBStjWngq38wbAAw==,iv:/qseLcYI9pESuDNxo/Hx7/y5+gZ4wYRrkN7C7vYJtQw=,tag:WmplMFBpg6e0ajRU1Cm4Qw==,type:str]
    redirectURIs:
      - https://vaultwarden.taila659a.ts.net/sso/oidc/callback
    trustedPeers:
      - "*"
  - name: Immich
    id: immich
    secret: ENC[AES256_GCM,data:WfS2mfWdVN8q1QxBxzQUmdlk4UwzuGwtYJ4dRzFoR6o=,iv:cSQWwtRcffkia2EMXEtcQNZhQJjMUiKP8lOYOdrpEUI=,tag:JN+of1qIEdk2wITtcPWWbQ==,type:str]
    redirectURIs:
      - https://immich.taila659a.ts.net/auth/login
    trustedPeers:
      - "*"
storage:
  type: memory
telemetry:
  http: 0.0.0.0:5558
web:
  gracefulShutdownTimeout: 5s
  healthz: 0.0.0.0:5556
  https: 0.0.0.0:5556
  tlsCert: /etc/ssl/private/tls.crt
  tlsKey: /etc/ssl/private/tls.key
sops:
  version: 3.13.3
  encrypted_regex: ^(secret|bindPW)$
  lastmodified: "2026-08-10T20:47:40Z"
  mac: ENC[AES256_GCM,data:VoxuP7jW1M0g9cP7/1EOzG+c5RIjRFD4qHUbfTG2Bn3ZuFYq/a3MG+WZv4YSsj7Ahl3qGa1a/qAHv8UFFR9pMzaD16L53u95xavjAY9EvQnLdYJI8IbHDd5/aI3DvpcWABU4xZso61fgz0SUFpppgPCI4P3RW44eC7sw74zXYWQ=,iv:7QYwUv9nMmHqJLgaWPYAt3qc6JaQSmcg4mlQX/AbpgQ=,tag:2HUm5cbCJIVZuL28Wx9nkA==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY29Ub3hTNERlMEhERG1C
        ai9yUEpYdDdEblYwV1M0N09NcHRCUTVwZ0Q0CmU4SU1QbmJWVkRacThYaVlZV291
        U2hZbGx0WSt1S25uU0FGUVVRN2dHMlkKLS0tIGdKQjNNVXY3cjRzRXczbTBVb2Z1
        d2NodnJ2RDBUTFJUQno0blhTeFNqQ1UKwZZLVSCNIxSD3wc346bgew9czbvRifQk
        F6C2Qr44oJcjrwKQ78loitlJzZmf2MkO9BGEx+OWi/Z8jlTpRIwG5w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OXI0NEFaSG4wL01Kc3p6
        NVcxOE00d2NoQ05HcndXYXNBQVJGUHR2Q0YwCmpZTnlPV3JFKzV2L3NBR2Y4T2Qr
        MFFPZFhnWW5QaVpBUkJ2SkpTOWxhQk0KLS0tIHoyRVJlSWN6MVRUMlFSV3pqMGh6
        dzAxUnAwekJUQUgwZU1Lb2FlYkgyTFUK+pT1DhBI05qzX86/3ps6UH9v34mREJP0
        +gFk65Y/avRzmfcEbtJ4EjdDhP+gHT9jGmmyTpF/at9YgyxLHUrOSg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUWM0Q0k2QWh1Ylh0QS9Y
        UFV6eVFjY0FobHJISmQwcGlmWGFlK3FWdkRZClljVWlLS1M4Ukd3ZDEyY0kyTFhF
        enUxMFpiT1lWdVd0YVlmcWlMejNxdk0KLS0tIGd6ZFZGSmdJcWR6cTYvYjNiT1I0
        eW8rZFp5TmI2bUJEbDgzSGdjak9ZZWcKcMWjCY4lGoqLOtA5yw8lnjIJnScazUkZ
        l2hyP0Rf3vIfGfSQqHM2ytdVG1inhlF0RFvp3HL3wkVFdDBQUdJvQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
