apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: llama-cpp-rpc-head
spec:
  endpoints:
    - fqdn:
        hostname: llama-cpp-rpc-head.shikanime.svc.cluster.local
        port: 9931
