resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
namespace: shikanime
patches:
  - patch: |-
      - op: add
        path: /spec/hostnames/-
        value: mautrix-signal.taila659a.ts.net
      - op: replace
        path: /spec/parentRefs
        value:
          - name: signal
            sectionName: http
    target:
      name: signal-redirect
      kind: HTTPRoute
  - patch: |-
      - op: add
        path: /spec/hostnames/-
        value: mautrix-signal.taila659a.ts.net
      - op: replace
        path: /spec/parentRefs
        value:
          - name: signal
            sectionName: https
    target:
      name: signal
      kind: HTTPRoute
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: communication
      app.kubernetes.io/instance: mautrix-signal
      app.kubernetes.io/name: mautrix-signal
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 0.2607.0
secretGenerator:
  - name: mautrix-signal
    files:
      - config.yaml=matrix-signal/config.enc.yaml
      - doublepuppet.yaml=matrix-signal/doublepuppet.enc.yaml
      - registration.yaml=matrix-signal/registration.enc.yaml
    options:
      disableNameSuffixHash: true
