resources:
  - netpol.yaml
  - httproute.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: vaultwarden
    newName: vaultwarden/server
    newTag: 1.37.1@sha256:ebdfe70701c60ac0c28c697e787cea767d7972940b786037b29fe0d507f821e8
