apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: llama-cpp
  namespace: shikanime
spec:
  serviceName: llama-cpp-kushira
  selector:
    matchLabels:
      app.kubernetes.io/process: llama-cpp-kushira
  template:
    metadata:
      labels:
        app.kubernetes.io/process: llama-cpp-kushira
    spec:
      nodeSelector:
        kubernetes.io/hostname: kushira
