resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
  - vmservicescrape.yaml
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: communication
      app.kubernetes.io/instance: mautrix-googlechat
      app.kubernetes.io/name: mautrix-googlechat
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 0.5.2
patches:
  - path: patch-netpol.yaml
    target:
      name: mautrix-googlechat
      version: v1
      kind: NetworkPolicy
secretGenerator:
  - name: mautrix-googlechat
    files:
      - config.yaml=matrix-googlechat/config.enc.yaml
      - doublepuppet.yaml=matrix-googlechat/doublepuppet.enc.yaml
      - registration.yaml=matrix-googlechat/registration.enc.yaml
    options:
      disableNameSuffixHash: true
patches:
  - path: patch-httproute.yaml
    target:
      name: googlechat
      version: v1
      kind: HTTPRoute

