apiVersion: ENC[AES256_GCM,data:aYo=,iv:Pv5G3QQVHd1eGsuM3+AvaVU/4Bi3nlmokd+15neY6s4=,tag:CLVx+OT0ej5+J07sS77Kig==,type:str]
kind: ENC[AES256_GCM,data:zcokJV/7,iv:G4O/PHKDqG/uBGrqjFHh+csZJmW5emjj9LbWBq0flXc=,tag:GpgGLkoJqxZ61aeYm0L+Yg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hcPMdbYwm1XWthDd,iv:RM5Y7WUJ5GjuoQVSVeED7naCGuYslwF5PceFsw/vIko=,tag:fJwoFxLUWvir1J/ZV3R2zg==,type:str]
    namespace: ENC[AES256_GCM,data:f5umIdaaKC4j7tHdAMT27mk=,iv:Ty0RfrYe3b7+7PNgZUip2cpxUqCfyYBgd/p8vVn6FUw=,tag:KKt5CwCo0MVrmnGC56IAfA==,type:str]
stringData:
    client_secret: ENC[AES256_GCM,data:X2/CNVYXfVeMCZXoo+h08ktxsToMLem0aw7npITSM0wJ120dwnnVc3Aw4NlDrIm6F07NS4nlGhXrssuFpFk96A==,iv:hzwQGSzB6YxQksukSkzoiyOkM2Ck4k/fJ/0UW4ZCU1M=,tag:iNwIFR7E8Y5vIaqSkwNKIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZ2lBeTNCZEtlaENpWWdF
            aGJYU3A1NUhXMW5VNkZYTjY2RDlXaG9MakRrCjF6MHYxWWlTVUJ4dy9Dc1owWXJP
            MHllNzEwSGg3ditIdkcyWVZyK2lRZWMKLS0tIE5oRCtnMjhGTjNrQ1NFd3czWTFo
            UlNGZENPcWJSTWp1STJYR29yR2Z3R2sKEIaTbCbL+E0qBhlZqpQofYf3QIgMMTJY
            nV9lBthPntobXnkD2adv3JrE7ybrrUO61mwetBswej2LlYCzLNtLiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN0Y5bjVkUzRneXlvMERU
            eUV4VVZ0OHpOQkVsYUw5cGc0TmlnZS9vS0U4CkJNNTZ6MjdnTDIwVG9LTDJOWmM4
            bThHOVBnZkUxdnFTbXI5MHJDTVhoY2MKLS0tIGIxQlNuTW5FMzNtbUtFendnS0Ro
            MnY3eDJFVE00R1FubU5GN3N3ZmgzRjAKQ9nnIIYbOHqAHWUQDRH2SATUfUl+I5DF
            B22AyoAAmjDZPe/MPfWwf+fltuD9ZbS5de+tH0pba3hgE/D/ffSYNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTXc2ZXVXdTlwNmVjY2tL
            NWxkdWtZSXZXTHhYOU11T3IveEZyU21kSTI0Cm9PREpNQ3JaWnhQTDBUQzJCS1o2
            ZkpNTjk2SFIrUWxZTFA3SUtTM05keUEKLS0tIDdvZm9ERVJ0WTg4VWRtUEs0M2N5
            K1MvUUFQS00vYThyQ3EyaCtqRGJuczAK2s2/xeId2fF1ipFGoMN1eccnZVpIGFVF
            c2WSnXYatcO/tfz0dk5Gt702jLeOvce2AA1TebLwCVZmykrZ4O9BNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
    lastmodified: "2026-09-23T16:36:53Z"
    mac: ENC[AES256_GCM,data:siYzNvol25El8dSwvPgsT4+RO623Vw2R4HojmkAGfGjO/6PbtCq81wsp373cCWmy+plpX42xyjXj3Mapq2NYZtKHCmATUxma4yXF+j/lrJgufjjOcFWxnCJVDaoFHyg2yNanufvThGKXMM+RMJ20wxqGQ6eVfdNRPae5UbNVBsM=,iv:fXQbiQDF2zyhBKN9YG2Fd2UZk90kU9PbWUkhFY0e/wQ=,tag:RBUkGu4O3H9/fR9uBm8jpQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
