resources:
  - ../../base
  - cert.yaml
  - gateway.yaml
namespace: shikanime
components:
  - ../../components/tls
patches:
  - path: patch-pvc.yaml
  - path: patch-sts.yaml
  - path: patch-httproute.yaml
  - path: patch-tcproute.yaml
  - path: patch-udproute.yaml
secretGenerator:
  - name: qbittorrent
    files:
      - qBittorrent.conf=qbittorrent/qBittorrent.enc.conf
