resources:
  - netpol.yaml
  - httproute.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: maintainerr
    newName: ghcr.io/maintainerr/maintainerr
    newTag: 3.26.0@sha256:0ff47e2465704ceb90cd79a1516844bc1c74f6c8eef8317988618a01e5a680ea
