apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime
resources:
  - gatewayclass.yaml
  - backends.yaml
  - route.yaml
secretGenerator:
  - name: envoy-ai-gateway-api-keys
    namespace: shikanime
    files:
      - nous-api-key.enc.env
      - openrouter-api-key.enc.env
