apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: qbittorrent
  namespace: shikanime
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: qbittorrent
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: qbittorrent
          tailscale.com/tags: "tag:web,tag:bittorrent"
