resources:
  - ../nishir
  - ingress.yaml
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: torrent-downloader
      app.kubernetes.io/instance: qbittorrent
      app.kubernetes.io/name: qbittorrent
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 5.1.4-2
patches:
  - path: patch-netpol.yaml
    target:
      name: qbittorrent
      version: v1
      kind: NetworkPolicy
  - path: patch-svc.yaml
