resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - backendtlspolicy.yaml
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: torrent-downloader
      app.kubernetes.io/instance: qbittorrent
      app.kubernetes.io/name: qbittorrent
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 5.2.3-1
patches:
  - target:
      name: qbittorrent
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [qbittorrent.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: qbittorrent
            sectionName: https
  - target:
      name: qbittorrent-redirect
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [qbittorrent.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: qbittorrent
            sectionName: http
  - path: patch-netpol.yaml
    target:
      name: qbittorrent
      version: v1
      kind: NetworkPolicy
