apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: meta
  namespace: shikanime
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: shikanime.dev/kernel-va
                        operator: NotIn
                        values:
                          - "39"
        container:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
      envoyService:
        name: meta
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: meta
          tailscale.com/tags: "tag:web"
