resources:
  - sts.yaml
  - vpa.yaml
images:
  - name: llama-cpp-rpc-worker
    newName: ghcr.io/shikanime-labs/machines/llama-cpp
    digest: sha256:eb6bde3e90a11b213f11e7ab793969b6e1ea1dfc6b7501e590644231e90ed3f2
