resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: version-control-server
      app.kubernetes.io/instance: forgejo
      app.kubernetes.io/name: forgejo
      app.kubernetes.io/part-of: nishir-platform
      app.kubernetes.io/version: 15.0.6-rootless
patches:
  - target:
      name: forgejo
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [forgejo.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: forgejo
            sectionName: https
  - target:
      name: forgejo-redirect
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [forgejo.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: forgejo
            sectionName: http
  - path: patch-netpol.yaml
    target:
      name: forgejo
      version: v1
      kind: NetworkPolicy
secretGenerator:
  - name: forgejo-config
    files:
      - app.ini=forgejo/app.enc.ini
