resources:
  - ../nishir
  - ingress.yaml
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: llm-inference
      app.kubernetes.io/instance: deepseek-v4-flash
      app.kubernetes.io/name: deepseek-v4-flash
      app.kubernetes.io/part-of: nishir-llm-serving
      app.kubernetes.io/version: "0731"
