apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: virt-operator
  namespace: kubevirt-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: virt-operator
  updatePolicy:
    updateMode: Auto
