apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIGatewayRoute
metadata:
  name: default
  namespace: shikanime
spec:
  rules:
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: qwen/qwen3.8-27b
      modelsOwnedBy: Shikanime Studio
      backendRefs:
        - name: llama-cpp
          priority: 0
          modelNameOverride: qwen/qwen3.8-27b
        - name: nous
          priority: 1
          modelNameOverride: qwen/qwen3.8-27b
        - name: openrouter
          priority: 2
          modelNameOverride: qwen/qwen3.8-27b
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: qwen/qwen3.8-flash
      modelsOwnedBy: Shikanime Studio
      backendRefs:
        - name: llama-cpp
          priority: 0
          modelNameOverride: qwen/qwen3.8-flash
        - name: nous
          priority: 1
          modelNameOverride: qwen/qwen3.8-flash
        - name: openrouter
          priority: 2
          modelNameOverride: qwen/qwen3.8-flash
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: deepseek/deepseek-v4-flash
      modelsOwnedBy: Shikanime Studio
      backendRefs:
        - name: llama-cpp
          priority: 0
          modelNameOverride: deepseek/deepseek-v4-flash-0731
        - name: nous
          priority: 1
          modelNameOverride: deepseek/deepseek-v4-flash-0731
        - name: openrouter
          priority: 2
          modelNameOverride: deepseek/deepseek-v4-flash-0731
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: z-ai/glm-5.3-flash
      modelsOwnedBy: Shikanime Studio
      backendRefs:
        - name: z-ai
          priority: 0
          modelNameOverride: glm-5.3-flash
        - name: llama-cpp
          priority: 1
          modelNameOverride: z-ai/glm-5.3-flash
        - name: nous
          priority: 2
          modelNameOverride: z-ai/glm-5.3-flash
        - name: openrouter
          priority: 3
          modelNameOverride: z-ai/glm-5.3-flash
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: qwen/qwen3-embedding-8b
      modelsOwnedBy: Shikanime Studio
      backendRefs:
        - name: llama-cpp
          priority: 0
          modelNameOverride: qwen/qwen3-embedding-8b
        - name: nous
          priority: 1
          modelNameOverride: qwen/qwen3-embedding-8b
        - name: openrouter
          priority: 2
          modelNameOverride: qwen/qwen3-embedding-8b
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: mistral/labs-leanstral-1-5
      modelsOwnedBy: Shikanime Studio
      backendRefs:
        - name: mistral
          priority: 0
          modelNameOverride: labs-leanstral-1-5
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: z-ai/glm-5.3
      modelsOwnedBy: Shikanime Studio
      backendRefs:
        - name: z-ai
          priority: 0
          modelNameOverride: glm-5.3
        - name: nous
          priority: 1
          modelNameOverride: z-ai/glm-5.3
        - name: openrouter
          priority: 2
          modelNameOverride: z-ai/glm-5.3
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: poolside/laguna-s-2.1
      modelsOwnedBy: Shikanime Studio
      backendRefs:
        - name: nous
          priority: 0
          modelNameOverride: poolside/laguna-s-2.1:free
        - name: openrouter
          priority: 1
          modelNameOverride: poolside/laguna-s-2.1:free
    - matches:
        - headers:
            - name: x-ai-eg-model
              type: RegularExpression
              value: ".*"
      modelsOwnedBy: Shikanime Studio
      backendRefs:
        - name: nous
          priority: 0
        - name: openrouter
          priority: 1
