---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: zai-key
  namespace: shikanime
spec:
  type: APIKey
  targetRefs:
    - name: zai
      group: aigateway.envoyproxy.io
      kind: AIServiceBackend
  apiKey:
    secretRef:
      name: inference-zai
      namespace: shikanime
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: openrouter-key
  namespace: shikanime
spec:
  type: APIKey
  targetRefs:
    - name: inference-openrouter
      group: aigateway.envoyproxy.io
      kind: AIServiceBackend
  apiKey:
    secretRef:
      name: inference-openrouter
      namespace: shikanime
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: mistral-key
  namespace: shikanime
spec:
  type: APIKey
  targetRefs:
    - name: mistral
      group: aigateway.envoyproxy.io
      kind: AIServiceBackend
  apiKey:
    secretRef:
      name: inference-mistral
      namespace: shikanime
