resources:
  - aigatewayroute.yaml
  - aiservicebackend.yaml
  - backend.yaml
  - backendsecuritypolicy.yaml
  - httproute.yaml
  - httproutefilter.yaml
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: llama-cpp
    newName: ghcr.io/shikanime-labs/machines/llama-cpp
    digest: sha256:49ffb3db0e955cb716402c4406872b6b2e5ceb7a9958bc01b89ce0d2da740765
configMapGenerator:
  - name: llama-cpp-models-preset
    files:
      - models-preset.ini=llama-cpp-models-preset/models-preset.ini
