resources:
  - aiservicebackend.yaml
  - backend.yaml
  - httproute.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: llama-cpp
    newName: ghcr.io/shikanime-labs/machines/llama-cpp
    digest: sha256:8ddc2d08fcee2af346b2ad3ff0695bb40948a12296c69072d6c7d7101f1f2812
  - name: huggingface
    newName: ghcr.io/shikanime-labs/machines/huggingface
    digest: sha256:68e5c95a2f748d960a7520d5aacd08f920449ba911bb421c51579050e841eed1
configMapGenerator:
  - name: llama-cpp-models-preset
    files:
      - models-preset.ini=llama-cpp-models-preset/models-preset.ini
  - name: llama-cpp-prefetch
    files:
      - entrypoint.sh=llama-cpp-prefetch/entrypoint.sh
