resources:
  - aigatewayroute.yaml
  - aiservicebackend.yaml
  - backend.yaml
  - backendsecuritypolicy.yaml
  - httproute.yaml
  - httproutefilter.yaml
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: llama-cpp
    newName: ghcr.io/shikanime-labs/machines/llama-cpp
    digest: sha256:0f2d5f4393f95ec0f07ce6eef51b34a3cfaf5903d8fe5512e58ab8fa4e152326
configMapGenerator:
  - name: llama-cpp-models-preset
    files:
      - models-preset.ini=llama-cpp-models-preset/models-preset.ini
