apiVersion: aigateway.envoyproxy.io/v1beta1
kind: MCPRoute
metadata:
  name: z-ai
  namespace: shikanime
spec:
  parentRefs:
    - name: inference
      kind: Gateway
      group: gateway.networking.k8s.io
  path: /mcp/z-ai
  backendRefs:
    - name: z-ai-web-reader
      kind: Backend
      group: gateway.envoyproxy.io
      path: /api/mcp/web_reader/mcp
      securityPolicy:
        apiKey:
          secretRef:
            name: inference-z-ai
            namespace: shikanime
    - name: z-ai-web-search-prime
      kind: Backend
      group: gateway.envoyproxy.io
      path: /api/mcp/web_search_prime/mcp
      securityPolicy:
        apiKey:
          secretRef:
            name: inference-z-ai
            namespace: shikanime
    - name: z-ai-zread
      kind: Backend
      group: gateway.envoyproxy.io
      path: /api/mcp/zread/mcp
      securityPolicy:
        apiKey:
          secretRef:
            name: inference-z-ai
            namespace: shikanime
