apiVersion: v1
kind: Service
metadata:
  name: llama-cpp
  namespace: shikanime
spec:
  sessionAffinity: ClientIP
  selector:
    app.kubernetes.io/instance: llama-cpp
    app.kubernetes.io/name: llama-cpp
  ports:
    - name: http
      appProtocol: http
      port: 9931
      protocol: TCP
      targetPort: http
