resources:
  - ../../base
  - cert.yaml
  - gateway.yaml
patches:
  - patch: "- op: add\n  path: /spec/hostnames\n  value:\n  - mautrix-linkedin.i.shikanime.studio\n- op: add\n  path: /spec/parentRefs\n  value:\n  - name: linkedin\n    sectionName: https"
    target:
      name: linkedin
      kind: HTTPRoute
  - patch: "- op: add\n  path: /spec/hostnames\n  value:\n  - mautrix-linkedin.i.shikanime.studio\n- op: add\n  path: /spec/parentRefs\n  value:\n  - name: linkedin\n    sectionName: http"
    target:
      name: linkedin-redirect
      kind: HTTPRoute
