apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: maintainerr-oidc-client
  namespace: shikanime
spec:
  targetRefs:
    - name: maintainerr
      kind: HTTPRoute
      group: gateway.networking.k8s.io
  oidc:
    provider:
      issuer: https://accounts.i.shikanime.studio
    clientID: maintainerr
    clientSecret:
      name: maintainerr-oidc-client
    redirectURL: https://maintainerr.i.shikanime.studio/oauth2/callback
