resources:
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: llama-cpp-rpc
    newName: ghcr.io/shikanime-labs/machines/llama-cpp
    digest: sha256:97c307c8bee48c968b9bfdb4cec82f59e1c9aad8b90d0ee8cb91dcb08ba47753
