resources:
  - nad.yaml
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: llama-cpp-rpc
    newName: ghcr.io/shikanime-labs/machines/llama-cpp
    digest: sha256:d12f356199725de26002c2895b0dfddc5f71d9b95f7dadbc6e8fab319079d7d0
