resources:
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: llama-cpp-rpc
    newName: ghcr.io/shikanime-labs/machines/llama-cpp
    digest: sha256:edefabce683d63aff90359338c150ac1c44d6eda1f92895c4312607815cfd547
