apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: llama-cpp-rpc
spec:
  config: |-
    {
      "cniVersion": "0.4.0",
      "name": "llama-cpp-rpc",
      "type": "macvlan",
      "master": "br1",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "datastore": "kubernetes",
        "range": "10.66.0.0/29",
        "range_start": "10.66.0.3",
        "range_end": "10.66.0.5"
      }
    }
