apiVersion: v1
kind: Service
metadata:
  name: llama-cpp-rpc
  namespace: shikanime
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: llama-cpp
    app.kubernetes.io/name: llama-cpp-rpc
  ports:
    - name: rpc
      port: 50052
      targetPort: rpc
