analytics:
  url: https://api.segment.io/v1/track
  token: null
  user_id: null
appservice:
  id: signal
  address: http://mautrix-signal.shikanime.svc.cluster.local:29328
  as_token: ENC[AES256_GCM,data:Sxg5Td2oTVAh+S2aodalgsGU3E2j93cfXurGjJbV6N4wwGfWoVgd8BaH37L+zk2iiKBgVjj8NthBVeM1ZACoMw==,iv:vNItCgEfFC+35HNmzZEw02ApaTvXpl9FPlxW7v1S5vU=,tag:NIiM7HRvl4xe/qa3LDUvJg==,type:str]
  async_transactions: false
  ephemeral_events: true
  hostname: 0.0.0.0
  hs_token: ENC[AES256_GCM,data:GVhpeykoEGyhyXB3WmwYA1qzhx3DlMt8iAB0ZCthnxXkAQ3KZ9Skcn38PGirGNMKRPUouusO9lYNUlHo8Hbc9Q==,iv:LFJQwicVDS6zZi/X0RmxXukWJTf6Y7YmLpM90pTZe/k=,tag:8Zs7cD5jaGrXxLN8z+zW4A==,type:str]
  port: 29328
  public_address: https://matrix-signal.taila659a.ts.net
  username_template: signal_{{.}}
  bot:
    avatar: mxc://maunium.net/wPJgTQbZOtpBFmDNkiNEMDUp
    displayname: Signal bridge bot
    username: signalbot
backfill:
  enabled: true
  max_catchup_messages: -1
  max_initial_messages: -1
  queue:
    batch_delay: 20
    batch_size: 100
    enabled: false
    max_batches: -1
    max_batches_override: {}
  threads:
    max_initial_messages: -1
  unread_hours_threshold: 720
bridge:
  async_events: false
  bridge_matrix_leave: false
  bridge_notices: false
  bridge_status_notices: errors
  cleanup_on_logout:
    bad_credentials:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
    enabled: false
    manual:
      private: nothing
      relayed: nothing
      shared_has_users: nothing
      shared_no_users: nothing
  command_prefix: "!signal"
  cross_room_replies: false
  deduplicate_matrix_messages: false
  mute_only_on_create: true
  no_bridge_info_state_key: false
  only_bridge_tags:
    - m.favourite
    - m.lowpriority
  permissions:
    "*": relay
    "@root:matrix.i.shikanime.studio": admin
    matrix.i.shikanime.studio: user
  personal_filtering_spaces: true
  private_chat_portal_meta: true
  relay:
    admin_only: true
    default_relays: []
    displayname_format: "{{ .DisambiguatedName }}"
    enabled: false
    message_formats:
      m.audio: "<b>{{ .Sender.DisambiguatedName }}</b> sent an audio file{{ if .Caption }}: {{ .Caption }}{{ end }}"
      m.emote: "* <b>{{ .Sender.DisambiguatedName }}</b> {{ .Message }}"
      m.file: "<b>{{ .Sender.DisambiguatedName }}</b> sent a file{{ if .Caption }}: {{ .Caption }}{{ end }}"
      m.image: "<b>{{ .Sender.DisambiguatedName }}</b> sent an image{{ if .Caption }}: {{ .Caption }}{{ end }}"
      m.location: "<b>{{ .Sender.DisambiguatedName }}</b> sent a location{{ if .Caption }}: {{ .Caption }}{{ end }}"
      m.notice: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.text: "<b>{{ .Sender.DisambiguatedName }}</b>: {{ .Message }}"
      m.video: "<b>{{ .Sender.DisambiguatedName }}</b> sent a video{{ if .Caption }}: {{ .Caption }}{{ end }}"
  resend_bridge_info: false
  split_portals: false
  tag_only_on_create: true
  unknown_error_auto_reconnect: null
database:
  type: sqlite3-fk-wal
  max_conn_idle_time: null
  max_conn_lifetime: null
  max_idle_conns: 1
  max_open_conns: 5
  uri: file:/data/signal.db?_txlock=immediate
direct_media:
  allow_proxy: true
  enabled: false
  media_id_prefix: null
  server_key: ENC[AES256_GCM,data:3o3jePFKu9TMLBxDxJR1sFiIR8abNlnd6/GErFBKyyu7pDm1lQJrstKvaKas9GwlgiQNWBXbUhpIkQ==,iv:ECLN0yo6rB4A2sNxTqPCZg3ja9XJwy6iNNTxF+X7JcQ=,tag:Rnovg6j5wK9VDwZxvd18zQ==,type:str]
  server_name: matrix-discord-media.taila659a.ts.net
  well_known_response: null
double_puppet:
  allow_discovery: false
  secrets:
    matrix.i.shikanime.studio: ENC[AES256_GCM,data:adnEFIId43atj/LYGj4stPA6QB7wxSvUwF8ITfn1dKOVnHZjH+0hGqsB7qtHp2DnE0Etg4gbrPXK5mXY21+BAUOLJ9oMUF1v+Q==,iv:1Epscy9j95xJFeKkILtEpPgGAMMf6/0YdGr9F0FhjMQ=,tag:driB676nMjNckQPz4iCe9A==,type:str]
  servers:
    anotherserver.example.org: https://matrix.anotherserver.example.org
encryption:
  allow: true
  allow_key_sharing: true
  appservice: false
  default: true
  delete_keys:
    delete_fully_used_on_decrypt: true
    delete_on_device_delete: true
    delete_outbound_on_ack: false
    delete_outdated_inbound: true
    delete_prev_on_new_session: true
    dont_store_outbound: true
    periodically_delete_expired: true
    ratchet_on_decrypt: true
  msc4190: false
  pickle_key: ENC[AES256_GCM,data:4g7qaKl1A5CpexIw4dsp8hNF2/WtUX/JWBYnpeYiV8i+MPBkEA7PkP5D4ZovxdgSJ5cVZ0yuEVi5OqCQJ8apFA==,iv:afUFJZzJ3FoqhljMQQps9n09fkbZ3AMGKYyaWjy2LLc=,tag:DDx7xxkZG55FpTMlXRYnFA==,type:str]
  require: false
  rotation:
    disable_device_change_key_rotation: false
    enable_custom: false
    messages: 100
    milliseconds: 6.048e+08
  self_sign: true
  verification_levels:
    receive: cross-signed-tofu
    send: cross-signed-tofu
    share: cross-signed-tofu
homeserver:
  address: https://synapse.shikanime.svc.cluster.local:8448
  async_media: false
  domain: matrix.i.shikanime.studio
  message_send_checkpoint_endpoint: null
  ping_interval_seconds: 0
  software: standard
  status_endpoint: null
  websocket: false
logging:
  min_level: debug
  writers:
    - type: stdout
      format: pretty-colored
    - type: file
      compress: false
      filename: ./logs/bridge.log
      format: json
      max_backups: 10
      max_size: 100
matrix:
  delivery_receipts: false
  federate_rooms: true
  message_error_notices: true
  message_status_events: false
  sync_direct_chat_list: true
  upload_file_threshold: 5.24288e+06
network:
  device_name: matrix-signal
  disappear_view_once: false
  displayname_template: '{{or .ProfileName .PhoneNumber "Unknown user"}}'
  location_format: https://www.google.com/maps/place/%[1]s,%[2]s
  note_to_self_avatar: mxc://maunium.net/REBIVrqjZwmaWpssCZpBlmlL
  number_in_topic: true
  sync_contacts_on_startup: true
  use_contact_avatars: false
  use_outdated_profiles: false
provisioning:
  allow_matrix_auth: true
  debug_endpoints: false
  enable_session_transfers: false
  shared_secret: ENC[AES256_GCM,data:7mwKAUtO2SIrplJEPHj0k8tFZw/Ufd+xTF2E5VKELm+tl0lhcBgflbdKHQ+X2rO+Sj54RzG6WqIixQCZ4kTwVA==,iv:bYlIunbaJUT9m7a/Zh47W5ar2zs/0WGAHleEyt66W1M=,tag:g7hArMePQeTGtwBaMH4YBQ==,type:str]
public_media:
  enabled: false
  expiry: 0
  hash_length: 32
  signing_key: ENC[AES256_GCM,data:ZnUP0Cq87aNdHKLASX8QySLXa7NSKx1HRDY4KMckT0rOjRkWiwYWyuA86tb7heDXorTGV5bdgluHws49ywFYGA==,iv:yvjuV+Y3ceL3obgQnwdjVBzSq200EeQNXwMohPbS/SM=,tag:z59GkKUNURZT1Cnrvj2VvA==,type:str]
sops:
  version: 3.13.3
  encrypted_regex: ^(avatar_proxy_key|as_token|hs_token|pickle_key|server_key|shared_secret|signing_key|login_shared_secret_map|secrets)$
  lastmodified: "2026-08-31T12:15:06Z"
  mac: ENC[AES256_GCM,data:n/xNa5+lUYSz00zggsXqb0S5Y5E2ex+tHKXHwNEYKWKMrnyTqLKeab2Pfefu0+fPqEwdd5AkUQD5ZtPQFImN9HAd7Mf2ronqQ3fisFtyvqpudXU2qoFPT8hEAXj4zRLONbVN99ww2sFeuJSl39IMC1V5GAuAkEcViX8+yc0dMc4=,iv:rdFentBLsH5a54XSO00mqK44nZW75u+iRC0T5MzsYp4=,tag:N7JQ/7Dhp8d1XQwgJi9h6g==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZElWQ1NHZi9zOHVpMUxS
        YitUeXBnTHVzM05ZcTAwRUxQbGllN2lZQWhVCmFKRzZOa3QrSFhyenUrVVhyM0E2
        TVlya1lnRS9ITjBRQXQ2Nml5SjdFdkUKLS0tIGQ1RGxvOXV2SHZEWHhONDkyUnVa
        V3NDUUpIV0FYbmw5N2lBVmlEV0ZpM0UKXtV2Vnnp/cGsfUUDgUBRy/E0j+Oqt/Ab
        x7WGcLNW5QMPzQVFNc4t3BDQ4sSY/0gDoKpxlOFASKfls2Zr30sBRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNVZXalFCdmg1NTFmUVVT
        aFBlMFlaWm5PblJmZmZrK0p4WHkxUUppbUgwCk9FWGF3YWE1SVlPSlQ2ZzJQQVlt
        bE11blNUU1Z0ZCtlWEFCVWdodWN6OVUKLS0tIDRNMm5ZNlBzREhVak1wdGRCek1L
        YkFtNXlWMTJEZTBGQUtNcnpPYnVUQ00Kq3/e7ULMQPVt5C96CyjAHXA8ox5NEz8H
        tgmL/eVlTBRHAUpZgcPTibzlibDYODGg5A81WOkUxO+hBsGADOAIjg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ1FKaUEzdkpnZTRCSkRn
        SlVIc29rQ0E1SG1IdnBFYk5Fc2VaZTV2QkY4CmNUd0NHRzRRYXg1OEFIQzRtcm1s
        SHFXK1Q0dUJsc01jVlVKb2tlY1V6L0UKLS0tIEJCcnAwTFlFeXdDM2ZITnJyendx
        aFhBeHBnOWcwM0s5S2NaeVlNejNFWlEKpHPx6mmItF12gJATgCuZbGZfdTQOycm+
        jhWLsxKLze/ntUJUODUcNnokCgjWLMT1miaE/r7uz54PNDprJRyI1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
