apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: sonarr
  namespace: shikanime
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: sonarr
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: sonarr
          tailscale.com/tags: "tag:syncthing"
