resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
namespace: shikanime
patches:
  - target:
      name: sonarr
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [sonarr.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: sonarr
            sectionName: https
  - target:
      name: sonarr-redirect
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [sonarr.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: sonarr
            sectionName: http
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: library-manager
      app.kubernetes.io/instance: sonarr
      app.kubernetes.io/name: sonarr
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 4.0.17
