resources:
  - httproutes.yaml
  - pvc.yaml
  - svc.yaml
  - vm.yaml
secretGenerator:
  - name: catbox-authorized-keys
    files:
      - authorized-keys/userdata
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/containerDisk/image
        value: ghcr.io/shikanime-labs/machines/catbox:dfe68d0e@sha256:ada4ae87373c3b97147057625a251f982df7e5f7889974f89e77797dbf2e2c5c
    target:
      name: catbox
      kind: VirtualMachine
