resources:
  - httproutes.yaml
  - pvc.yaml
  - svc.yaml
  - vm.yaml
secretGenerator:
  - name: catbox-authorized-keys
    options:
      disableNameSuffixHash: true
    files:
      - authorized-keys/userdata
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/containerDisk/image
        value: ghcr.io/shikanime-labs/machines/catbox:c1d1324f@sha256:a1fc274828cbf5be22a6ead2769f1e5675ec5c2a381e98b293e80f9461e42fe7
    target:
      name: catbox
      kind: VirtualMachine
