apiVersion: v1
kind: Service
metadata:
  name: catbox
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: catbox
    app.kubernetes.io/name: catbox
  ports:
    - name: ssh
      appProtocol: ssh
      port: 22
      targetPort: ssh
    - name: mdns
      appProtocol: mdns
      port: 5353
      protocol: UDP
      targetPort: mdns
    - name: dashboard
      appProtocol: http
      port: 9119
      targetPort: dashboard
    - name: a2a
      appProtocol: http
      port: 9900
      targetPort: a2a
    - name: api-server
      appProtocol: http
      port: 8642
      targetPort: api-server
