apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
spec:
  template:
    spec:
      initContainers:
        - name: config-sync
          image: rclone
          args:
            - copyto
            - --copy-links
            - /mnt/startup-config/LDAP-Auth.xml
            - /mnt/config/plugins/configurations/LDAP-Auth.xml
          command:
            - rclone
          volumeMounts:
            - name: config
              mountPath: /mnt/config
            - name: rclone-config
              mountPath: /config/rclone/rclone.conf
              readOnly: true
              subPath: rclone.conf
            - name: startup-config
              mountPath: /mnt/startup-config
              readOnly: true
          securityContext:
            capabilities:
              add:
                - FOWNER
      containers:
        - name: jellyfin
          volumeMounts:
            - name: rclone-config
              mountPath: /config/rclone/rclone.conf
              readOnly: true
              subPath: rclone.conf
      volumes:
        - name: rclone-config
          configMap:
            name: jellyfin-rclone
        - name: startup-config
          secret:
            secretName: jellyfin-ldap
