resources:
  - ../../base
  - cert.yaml
  - gateway.yaml
namespace: shikanime
patches:
  - path: patch-pvc.yaml
  - path: patch-sts.yaml
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - seerr.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: seerr
          sectionName: https
    target:
      name: seerr
      kind: HTTPRoute
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - seerr.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: seerr
          sectionName: http
    target:
      name: seerr-redirect
      kind: HTTPRoute
