apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: hermes-agent
  namespace: shikanime
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: hermes-agent
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: hermes-agent
          tailscale.com/tags: "tag:web"
