---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: automata
spec:
  defaultBackend:
    service:
      name: hermes-agent
      port:
        name: api-server
  ingressClassName: tailscale
  tls:
    - hosts:
        - automata
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: automata-a2a
spec:
  defaultBackend:
    service:
      name: hermes-agent
      port:
        name: a2a
  ingressClassName: tailscale
  tls:
    - hosts:
        - automata-a2a
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nishir
spec:
  defaultBackend:
    service:
      name: hermes-agent
      port:
        name: api-server
  ingressClassName: tailscale
  tls:
    - hosts:
        - nishir
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: automata-dashboard
spec:
  defaultBackend:
    service:
      name: hermes-agent
      port:
        name: dashboard
  ingressClassName: tailscale
  tls:
    - hosts:
        - automata-dashboard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: automata-webhook
  annotations:
    tailscale.com/funnel: "true"
    tailscale.com/tags: tag:web
spec:
  defaultBackend:
    service:
      name: hermes-agent
      port:
        name: webhook
  ingressClassName: tailscale
  tls:
    - hosts:
        - automata-webhook
