resources:
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: immich-machine-learning
    newName: ghcr.io/immich-app/immich-machine-learning
    newTag: v1.118.0
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "immich-machine-learning", "tag-regex":
      "^(?P<version>\\d+\\.\\d+\\.\\d+)$" } ]'
