resources:
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: immich-machine-learning
    newName: ghcr.io/immich-app/immich-machine-learning
    newTag: v3.3.1-openvino@sha256:9f5ea923b763435592280e2f5e051a62f1a33d6d14e87620fc15453c27a12ae0
