resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: photo-manager
      app.kubernetes.io/instance: immich
      app.kubernetes.io/name: immich
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: v1.118.0
secretGenerator:
  - name: immich-config
    files:
      - config.yaml=immich/config.enc.yaml
    options:
      disableNameSuffixHash: true
patches:
  - path: patch-netpol.yaml
    target:
      name: immich
      version: v1
      kind: NetworkPolicy
patches:
  - path: patch-httproute.yaml
    target:
      name: immich
      version: v1
      kind: HTTPRoute

