apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lldap-tls
spec:
  commonName: lldap
  dnsNames:
    - lldap
    - lldap.shikanime
    - lldap.shikanime.svc.cluster.local
  issuerRef:
    name: nishir
    kind: ClusterIssuer
  secretName: lldap-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-lldap
  namespace: shikanime
spec:
  commonName: lldap.i.shikanime.studio
  dnsNames:
    - lldap.i.shikanime.studio
  issuerRef:
    name: studio-shikanime
    kind: ClusterIssuer
  secretName: studio-shikanime-i-lldap
  usages:
    - digital signature
    - key encipherment
    - server auth
