resources:
  - ../../base
namespace: shikanime
patches:
  - path: patch-sts.yaml
    target:
      name: lldap
      kind: StatefulSet
secretGenerator:
  - name: lldap
    envs:
      - lldap/.enc.env
