apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authelia
spec:
  template:
    spec:
      containers:
        - name: authelia
          livenessProbe:
            httpGet:
              scheme: HTTPS
          readinessProbe:
            httpGet:
              scheme: HTTPS
          startupProbe:
            httpGet:
              scheme: HTTPS
          env:
            - name: X_AUTHELIA_SERVER_TLS_KEY
              value: /etc/ssl/private/tls.key
            - name: X_AUTHELIA_SERVER_TLS_CERTIFICATE
              value: /etc/ssl/private/tls.crt
          volumeMounts:
            - name: tls
              mountPath: /etc/ssl/private
              readOnly: true
      volumes:
        - name: tls
          secret:
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                mode: 416
                path: tls.key
            secretName: authelia-tls
