resources:
  - ../nishir
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: ldap-provider
      app.kubernetes.io/instance: lldap
      app.kubernetes.io/name: lldap
      app.kubernetes.io/part-of: nishir-platform
      app.kubernetes.io/version: 2026-08-08
