resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - httproute.yaml
namespace: shikanime
patches:
  - path: patch-httproute-lldap.yaml
    target:
      name: lldap
      kind: HTTPRoute
  - path: patch-httproute-lldap-redirect.yaml
    target:
      name: lldap-redirect
      kind: HTTPRoute
  - path: patch-netpol.yaml
    target:
      name: lldap
      kind: NetworkPolicy
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: ldap-provider
      app.kubernetes.io/instance: lldap
      app.kubernetes.io/name: lldap
      app.kubernetes.io/part-of: nishir-platform
      app.kubernetes.io/version: 2026-08-08-debian
