resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - httproute.yaml
namespace: shikanime
patches:
  - path: patch-netpol.yaml
    target:
      name: lldap
      kind: NetworkPolicy
  - target:
      name: lldap
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [lldap.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: lldap
            sectionName: https
  - target:
      name: lldap-redirect
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [lldap.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: lldap
            sectionName: http
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: ldap-provider
      app.kubernetes.io/instance: lldap
      app.kubernetes.io/name: lldap
      app.kubernetes.io/part-of: nishir-platform
      app.kubernetes.io/version: 2026-08-08-debian
