apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: discord
spec:
  gatewayClassName: discord
  listeners:
    - name: http
      port: 80
      protocol: HTTP
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: discord-i-shikanime-studio-tls
            group: ""
            kind: Secret
