resources:
  - ../nishir
  - ingress.yaml
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: library-manager
      app.kubernetes.io/instance: radarr
      app.kubernetes.io/name: radarr
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 6.2.1
patches:
  - path: patch-netpol.yaml
    target:
      name: radarr
      version: v1
      kind: NetworkPolicy
