resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
namespace: shikanime
patches:
  - path: patch-httproute-radarr.yaml
    target:
      name: radarr
      kind: HTTPRoute
  - path: patch-httproute-radarr-redirect.yaml
    target:
      name: radarr-redirect
      kind: HTTPRoute
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: library-manager
      app.kubernetes.io/instance: radarr
      app.kubernetes.io/name: radarr
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 6.2.1
