apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: grafana
  namespace: monitoring-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: grafana
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: grafana
          tailscale.com/tags: "tag:web"
