apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: llama-cpp
  namespace: shikanime
spec:
  schema:
    name: OpenAI
  backendRef:
    name: llama-cpp
    kind: Backend
    group: gateway.envoyproxy.io
