resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: postgres
    newName: tensorchord/pgvecto-rs
    newTag: pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "immich-postgres", "tag-regex": "^(?P<version>.+)$" } ]'
