resources:
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: postgres
    newName: ghcr.io/immich-app/postgres
    newTag: 16-vectorchord0.4.3-pgvectors0.2.0@sha256:1a078b237c1d9b420b0ee59147386b4aa60d3a07a8e6a402fc84a57e41b043a4
