resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: postgres
    newName: tensorchord/pgvecto-rs
    newTag: pg14-v0.2.0
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "immich-postgres", "tag-regex": "^(?P<version>.+)$" } ]'
