apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
spec:
  type: ExternalName
  externalName: immich-postgres-rw.shikanime-postgres.svc.cluster.local
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
