resources:
  - httproute.yaml
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: sonarr
    newName: lscr.io/linuxserver/sonarr
    newTag: 4.0.19@sha256:82172b363f9eddc02aca544f880a044f2ceb9aaf190bc87e4454e2f705eb91d0
