apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: honcho
  namespace: shikanime
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: honcho
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: honcho
          tailscale.com/tags: "tag:syncthing"
