resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: rclone
    newName: rclone/rclone
    newTag: 1.75.0@sha256:b06aed988cf5967de7c25be5925240983981c757f4ed1ac9d2fa659d51d60548
  - name: hermes-agent
    newName: nousresearch/hermes-agent
    newTag: v2026.8.27@sha256:e3f4f0679f15556d5e09369cc36bf1074351b2d37bdd672dae593dfd07495180
configMapGenerator:
  - name: hermes-agent-rclone
    files:
      - rclone/rclone.conf
