resources:
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: rclone
    newName: rclone/rclone
    newTag: 1.75.0@sha256:b06aed988cf5967de7c25be5925240983981c757f4ed1ac9d2fa659d51d60548
  - name: hermes-agent
    newName: ghcr.io/shikanime-labs/machines/hermes-agent
    newTag: latest@sha256:585b98776439aa721a89fc4650285f70f59278b91e9b8d0b8f77bb2e55eff6dc
configMapGenerator:
  - name: hermes-agent-rclone
    files:
      - hermes-agent-rclone/rclone.conf
