resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: rclone
    newName: rclone/rclone
    newTag: 1.75.0@sha256:b06aed988cf5967de7c25be5925240983981c757f4ed1ac9d2fa659d51d60548
  - name: hermes-agent
    newName: nousresearch/hermes-agent
    newTag: v2026.8.27@sha256:5f23552e16589d291099cd8041233e6200197d225e4b28b22a0463e732d4b843
metadata:
  annotations:
    automata.shikanime.studio/images: '[ { "name": "hermes-agent", "tag-regex": "^(?P<version>.+)$" } ]'
configMapGenerator:
  - name: hermes-agent-rclone
    files:
      - rclone/rclone.conf
