---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-agent-profiles-data
spec:
  resources:
    requests:
      storage: 16Gi
  volumeMode: Filesystem
  storageClassName: longhorn-standard
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-agent-skills-data
spec:
  resources:
    requests:
      storage: 512Mi
  volumeMode: Filesystem
  storageClassName: longhorn-standard
  accessModes:
    - ReadWriteMany
