issuer: https://accounts.taila659a.ts.net
enablePasswordDB: true
oauth2:
    skipApprovalScreen: true
staticClients:
    - name: Shikanime
      id: REPLACE_WITH_CLIENT_ID
      secret: ENC[AES256_GCM,data:8Nu0JERKlqXZYgCaWo/oanWozI/pVI9V4Oo=,iv:CdMuKAPmIPeNTmmLTKc8/2g+9/S5c11cckwTxSqgwo4=,tag:3kophb6uEm1ZDQjbqvZNIw==,type:str]
      redirectURIs:
        - https://accounts.taila659a.ts.net/callback
      trustedPeers:
        - '*'
    - name: Forgejo
      id: forgejo
      secret: ENC[AES256_GCM,data:yxDGz7WqMpoAwKywLJf0nJrsnrPXrvBs95ozioeUlUWenfsZ0QKN+tc4uOmUYM3YD0Q9+4NFwgMgkFa5B8YSCQ==,iv:/QKUM0Q0WP6M5z4E9VnLJAN9Laaa3HaoKJ0vTc4uOEQ=,tag:nlk+2n5JnhIzyF+iE/wYVA==,type:str]
      redirectURIs:
        - https://forgejo.taila659a.ts.net/user/oauth2/dex/callback
      trustedPeers:
        - '*'
storage:
    type: memory
telemetry:
    http: 0.0.0.0:5558
web:
    gracefulShutdownTimeout: 5s
    healthz: 0.0.0.0:5556
    http: 0.0.0.0:5556
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrb2E2WTJ6eTluaFR3WjBR
            NThsR25Gb1ZoL2ZDdnFXMy9qdGovK3kwTUhBClloaFpzbUh1TVVGSTZOZEJuUnR2
            OVVDcmtaa1JFbHF3ZFBGN0JJcTJNK3MKLS0tIGlRVXRFTmJHRGpFaDBLellEMWxu
            Y1M5cE4wL2FWYnpMbkFuclh2ZkdQbmMK9IvzOIQ0GrMxPf9bnlqIjPpdC7TFY1qR
            NfO5nUgwu7sfRiQ/JPij0gXpvm5lxGhRi65tI2UsH8TgdvZlV/ZdPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeERvMzlVdXBBTG5YYjFL
            SjJHNXhEL2NQMGxnc2pjSmZ1V2dFbjhTVERZCmxYdEE4RFU1MnpsZWNUdWxjOVhP
            d2J1b3Vac0xxRUlmQmZZOVFLRUtSVEEKLS0tIFl6RG1ocUVDNDJIS3hvTytDZHpD
            RU1iRGNVUmpyU3ZEWmJwVGowM3lmZFUKu2YMoA3WWlj7cR9s4O2vJ/tGzBU2duBM
            nSJOLLaXmPfoPZtQo2aIjpHAsc+0AD91+eLSfRepUTw1ad+WsmP5fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbnhWMzNqNUNmUDVkYkRI
            NmZyRXZUN090c0tId1BxYVVXZGtNMVkyNHlJCkJybys5dkh2MGtxdEwrczFkK0dz
            ODY1aEJUYnlSYVk0a3A2SnFNdGluaWMKLS0tIDViVkppam5ycmxSUGJDdUE2Y1hz
            S1pyV24zeU1hZUF1dW92ZlYyUnZXQVEKSEb1rLO1Rrx/TK8weAtwkFj+wYVGttHb
            Ovth4i7aTeu0d2iM9SIiFWLtAXUnVIm5RygQo/XY+72Fxc6p4cOOtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
    encrypted_regex: secret$
    lastmodified: "2026-08-08T21:44:21Z"
    mac: ENC[AES256_GCM,data:RpzvePpML6U+ZxbIOwfpb5w97u9ZTIEzBW7DTcGPDt2JdEe8QttwH9VbTcwM+WpGJzqIMRd0xJbnyqU3kY1m8CGsN87n15vguUl9hCr6IUUQodg/rYrixwZeNIzBRDNRpUVRIF/FowG59El8JruD36b/2CVt5AmlD2XlaJNFy0U=,iv:O0lqZVsYiRjbGUuqSldALMKoOAusJhS7t/h0LpeWVtI=,tag:DXYV1nHaBPZ4O8YozAqt8Q==,type:str]
    version: 3.13.1
