apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: inference
  namespace: shikanime
spec:
  tls:
    clientValidation:
      caCertificateRefs:
        - name: nishir-ca-certificates.crt
          group: ""
          kind: ConfigMap
  connection:
    bufferLimit: 8Mi
