apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: inference
  namespace: shikanime
spec:
  targetRefs:
    - name: inference
      group: gateway.networking.k8s.io
      kind: Gateway
  connection:
    bufferLimit: 8Mi
