resources:
  - ../../base
  - ../../components/monitoring
  - cert.yaml
  - clienttrafficpolicy.yaml
  - gateway.yaml
namespace: shikanime
components:
  - ../../components/tls
configurations:
  - namereference.yaml
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: inference
      app.kubernetes.io/instance: llama-cpp
      app.kubernetes.io/name: llama-cpp
      app.kubernetes.io/part-of: nishir-inference
      app.kubernetes.io/version: "3.8"
secretGenerator:
  - name: inference-z-ai
    namespace: shikanime
    envs:
      - inference-z-ai/.enc.env
  - name: inference-nous
    namespace: shikanime
    envs:
      - inference-nous/.enc.env
  - name: inference-openrouter
    namespace: shikanime
    envs:
      - inference-openrouter/.enc.env
  - name: inference-mistral
    namespace: shikanime
    envs:
      - inference-mistral/.enc.env
patches:
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - chat.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: llama-cpp
          sectionName: https
    target:
      name: llama-cpp
      kind: HTTPRoute
  - patch: |-
      - op: add
        path: /spec/parentRefs
        value:
          - name: inference
            kind: Gateway
            group: gateway.networking.k8s.io
    target:
      name: default
      version: v1beta1
      group: aigateway.envoyproxy.io
      kind: AIGatewayRoute
  - patch: |-
      - op: add
        path: /spec/tls
        value:
          sni: llama-cpp.shikanime.svc.cluster.local
          caCertificateRefs:
            - group: ""
              kind: ConfigMap
              name: nishir-ca-certificates.crt
    target:
      name: llama-cpp
      kind: Backend
