apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: llama-cpp
spec:
  template:
    spec:
      containers:
        - name: llama-cpp
          envFrom:
            - secretRef:
                name: llama-cpp-env
