apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama-cpp-cache
spec:
  capacity:
    storage: 512Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/cache/huggingface
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: feature.node.kubernetes.io/pci-0380_1002.present
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-huggingface
spec:
  volumeName: llama-cpp-cache
  accessModes:
    - ReadWriteOncePod
  storageClassName: ""
  resources:
    requests:
      storage: 512Gi
