apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: inference
  namespace: shikanime
spec:
  gatewayClassName: inference
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        options:
          gateway.envoyproxy.io/mtls: "true"
        certificateRefs:
          - name: inference-tls
  infrastructure:
    parametersRef:
      name: inference
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
