resources:
  - ../nishir
  - gatewayclass.yaml
  - gateway.yaml
  - envoyproxy.yaml
  - ingress.yaml
  - netpol.yaml
namespace: shikanime
components:
  - ../../components/tls
patches:
  - target:
      name: inference-tls
      kind: Certificate
      namespace: shikanime
    path: patch-cert.yaml
  - target:
      name: default
      kind: AIGatewayRoute
      namespace: shikanime
    path: patch-aigatewayroute.yaml
secretGenerator:
  - name: inference-nous
    namespace: shikanime
    options:
      disableNameSuffixHash: true
    envs:
      - inference-nous/.enc.env
  - name: inference-openrouter
    namespace: shikanime
    options:
      disableNameSuffixHash: true
    envs:
      - inference-openrouter/.enc.env
  - name: inference-mistral
    namespace: shikanime
    options:
      disableNameSuffixHash: true
    envs:
      - inference-mistral/.enc.env
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: inference
      app.kubernetes.io/instance: llama-cpp
      app.kubernetes.io/name: llama-cpp
      app.kubernetes.io/part-of: nishir-inference
      app.kubernetes.io/version: "3.8"
