apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: llama-cpp
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    name: llama-cpp
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    namespace: shikanime
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: llama-cpp
  namespace: shikanime
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: shikanime.dev/kernel-va
                        operator: NotIn
                        values:
                          - "39"
        container:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
      envoyService:
        name: llama-cpp
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: llama-cpp
          tailscale.com/tags: "tag:web"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: llama-cpp
spec:
  gatewayClassName: llama-cpp
  listeners:
    - name: http
      port: 80
      protocol: HTTP
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: studio-shikanime-i-chat
            group: ""
            kind: Secret
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: llama-cpp-redirect
spec:
  hostnames:
    - chat.i.shikanime.studio
  parentRefs:
    - name: llama-cpp
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
