apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-ml
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/pci-0300_8086.present
                    operator: In
                    values:
                      - "true"
      containers:
        - name: immich-ml
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          env:
            - name: IMMICH_MACHINE_LEARNING_GPU_ACCELERATION
              value: "true"
          volumeMounts:
            - name: dev-dri
              mountPath: /dev/dri
      volumes:
        - name: dev-dri
          hostPath:
            type: Directory
            path: /dev/dri
