resources:
  - ../nishir
  - ingress.yaml
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: library-manager
      app.kubernetes.io/instance: seerr
      app.kubernetes.io/name: seerr
      app.kubernetes.io/part-of: nishir-media
      app.kubernetes.io/version: 3.3.0
patches:
  - path: patch-netpol.yaml
    target:
      name: seerr
      version: v1
      kind: NetworkPolicy
