telemetry:
    metrics:
        enabled: true
        address: tcp://0.0.0.0:9959/metrics
storage:
    local:
        path: /config/db.sqlite3
    encryption_key: ENC[AES256_GCM,data:WnU7ZuoRUHvVKiz8FikzohPOhkRMoqDYsNcJUwKPl6jCmhAswnFy8egPgNwQBEkXB90b8fZas6vFYzlN8QeaIZGUDP2lP4g=,iv:DeTTUuJZJrX2tFPt8u0OO78Z5GkLrrXSqzxCFRQCuz8=,tag:KcpLcy23lEcbPzTPFEgcVQ==,type:str]
session:
    inactivity: 15m
    expiration: 12h
    remember_me: 1w
    cookies:
        - domain: i.shikanime.studio
          authelia_url: https://accounts.i.shikanime.studio
        - domain: taila659a.ts.net
          authelia_url: https://accounts.taila659a.ts.net
    secret: ENC[AES256_GCM,data:VUMzG/4dADIt8F0TKy/xoQ8LNRJ9fXQIMXLyNhPFNYrQowQ36CYRsxIPDnHyXWd1xP5BjSWJt3c0hRg15q/PBw==,iv:4m/nfQhG5vjYlZWLJlQU+4OU+h4lrzT8R51kNSOyntE=,tag:KMSSCweHiAzZk+wqW0MUvA==,type:str]
authentication_backend:
    ldap:
        address: ldaps://lldap.shikanime.svc.cluster.local:6360
        timeout: 5s
        tls:
            server_name: lldap.shikanime.svc.cluster.local
        base_dn: dc=shikanime,dc=studio
        additional_users_dn: ou=people
        users_filter: (&({username_attribute}={input})(objectClass=person))
        additional_groups_dn: ou=groups
        groups_filter: (member={dn})
        user: uid=admin,ou=people,dc=shikanime,dc=studio
        password: ENC[AES256_GCM,data:obvwu5Il0ebVjpvbvXe7kAiRvFmN6JEL7plhdQ==,iv:v9pNpdGJOSS3AOud/1kaO6gOsGuk/9sUd3mw0yVbRhs=,tag:dTCA/hefu9hEvySppPPyBw==,type:str]
identity_providers:
    oidc:
        hmac_secret: ENC[AES256_GCM,data:Ig1wJ/fsTPMlE9IzZOXWQc05pxb6JCbICGNGsyn2/Ar2jj8vOOsSLwwOnbXb3NCnhsjb3mCmrTfTeRzRm6H1HA==,iv:qlF8hTVzBqwldP/uS0TPS43/psQTEIeuPz6JVVvlDwE=,tag:hgQ+y//BAzX68tqqz9Hskw==,type:str]
        jwks:
            - key: ENC[AES256_GCM,data:AZHtHoRlq3yyCPROBlk3dEnlGONpwVWPN+q0dwRvdVxhB3UuBmI7k60W5skn4oCby9F/CUkoMF3+8+Mbznf3VpquMO5M1OEf50apvyqkLw9MK978yQaqS9P1gBeeI7SqbWGEC2mQVVh3rtAlaTubBOcPm5yOBLs3ERB9y3h0KnpF+mzcJuskmL5+kSU0rQNE90MyZtFt1/mtTrQmAIPoAibM+vQ14fcB5xE4/ioN2O20H22vvZjh3swFS8iwKA0h1blfZ+kzwQAbCy1rzni9x13eGJfF1EhchdcSUgBIZwVbBRF1CieOOkoyPGThC/Vi0utJ0dpH7OP+Cd6MWICK7ZvEdNkBbJIbJmF/Sq6HCyhD/ojh7bFSSkWmrn2tJaWL/9jeK7Rb5E2/c5jtZ2DHGWMhGpIk3auXJhoe+LpWyXxp42r8KGUZi4YjBbQghbKSVOvsYiX6xD8CvFiVulgJvNDthZyMURov/OQtlgkZZsPjF9HL0jx04jk05ltoEUeTvi10tSP5F8KomE/0hn6ubobn1SxCaVVMXinCp1mqcxlR00cksp1w1pecrn7oHwgBsYjGfVXi0khm6g3d3D1ULmRBRpflfYkuHakB8LfXxZWUVPTiy66k6IGEKWCXIX2WaJ4yVeNGpy+bIn0a/ZUqcr4V0gfqsh1MRCskTNhY+0m9N7h3UMVLbqU4KFHadOJjfkXQdZ2gJs78QPdOzRQ8zstPgzCoCRIRzt5SbnMAD2Iqt1thYto3vhTZfBjIUMVyp23j+yoAGFMlAQT2aYzOzphQ3aLMkzkiDhqbzxoFEqwNkKO79a3bVfcwe0nQLX3RW/buTum36r8/EzSPeY9fSnA2TD/kIBXsBWQ746VvdrHheqZPo0HsHQIfcVUOBq+JswNRqCwX4rYulodGwx9IYY0iiWyv02Hj4m3IWIIVcHxQk3jxtDQU3s4d7r/szJP9ltg4JRDrueFpsOMQm4b7Ml288DrxWMZHB+OszwyUi4xsbgE7D6w5dIZsiYl0kPD69PI37+XtUeNz//F3TdRiYOJa2mHjhbspAV0GIZbWFcP31s+DemiNd2xVwDNkBf901s7u0gFcF3LNOdO8NKw7X6FuhXArFyUjaajvgVNgs+gXt9R2MlvwIHNoM9tzecDWsGy+6fBbZ0vy7U7QWrRXRjmEf2W1mhlj2I4Apc1pH4OotUbZLz6eIplmAYS6dx6QHoqmdfTIEYLgm89WF+hKNtsSMIbPqyBXbMFVYyZ1qH1SWaZgn2sCwByug89Q2PI/c6C+NWbQIbZDAq53Afbmmmhasqugur1UVqD5SeqH0wJKA6Ykx4AvhVO6LJKP0qI1/T0kgRV696iJbHHLH5RllNuVLefMYLLoBTj4+kdSTTsAxC3yx11v2EJnv+hK8MB703yz8+3fDKQ05oo0H4zSnRucLmJXOSatDAvxy8lRA24ow7YPmO3aAvILsm0PCj7s4vb/XieP4ue/OV8/eRrG0ogmTiFcLOHhBjMDMSRZgXCNZ0XHhL7mUVbNv5vDA51yqkEFxNSzukzWNVsRzQ1urbu0N5DvxFDYNlbd2ytn4JjLSh5XoYYEoLSw3Fc13KXsDUX8mUFFsQO85HD1Agc69No4qPN2ClpoqP2hz5Fg04yav43W+vWmA/xtKeTFnK/BRmZ0waANbCR4vZEiA0c1W+H3+iEcCQTm8x2P+cwNWPJGY0NCKTn8QSAYOL/kS7ahzg/+4diMHNy4qLkgW75bJyneWue9pkDJCf1PH0iZSsJJbnCxCrPJedMGTiHe1hPn+HS3ydj3qBGulhYUxqZ0nf+/MhdNuxJrZZHToT4WJ0kdmZa8IY7FjZKjyK/6LSJzDlFqssFsja14ZeEN0H88zKJWkvwjQOpDaNfgHGarVeQBaEfL099WpyM/oaGGEQ6FsgY0RukghEPk/aHdTz+HZ2bnFR1PqL9gxHzpREnYLDsi14ugJAimYLb52p3p+c7sW26oj81XoyXh+Au3HHfefmOUStPWKCje+XQwS7zBDFsBP4VYyJT067pmeOLFGG+uEgqMFtoNNcVvAnmJms+sLwqIg9Y+k/38gz243rv7Cp0askwb0jqMrdg+T19G7Swo4RNLRkr+O77EUwb6/EyCmA8UqLY/S+PcARMMQIOBgl3YPbpQ9nP021PGOG9zTer5O3sHPrUxFXCj5YTpNE04dYACjqeYxxnuIjD3d1ZWxeeSWULd/U3r1Vd6TwdNa4iAAnZbwaTWUD/aAgWwIlMExyie6MvOOBMd,iv:5syA3IPMYW86OBV1j2N8NNQmitnb0EmGx8u5jOCXK98=,tag:meMUBeU4rKW3unZKmYc0eQ==,type:str]
              key_id: authelia-rs256
              algorithm: RS256
              use: sig
        clients:
            - client_id: forgejo
              client_name: Forgejo
              redirect_uris:
                - https://forgejo.i.shikanime.studio/user/oauth2/Dex/callback
              authorization_policy: two_factor
              client_secret: ENC[AES256_GCM,data:4B0duQGEq3Tq0KYxg6VpZn8L6LQSBE+xCAnwSPQbHmYp+xicLSylB1Rty17JPEsGG+WVH/fRHrH/34GFbOT1HB4SBBTFfFHo3+U894jwo44P/n1nJHSeuQTxLw5lMBn2/slRTwgMR0I6ZZ7ngDMoIZA0nxmeGa2xfQId9HM9kmRDgfI=,iv:iwxWy29baz0b8M0h6iSQ/ih3SaEqKgK171As5TdTeGw=,tag:RvLbESxrFhK4kAjz9k8gVg==,type:str]
            - client_id: gitea-mirror
              client_name: Gitea Mirror
              redirect_uris:
                - https://gitea-mirror.i.shikanime.studio/api/auth/sso/callback/dex
              authorization_policy: two_factor
              client_secret: ENC[AES256_GCM,data:SI2O5n6fNZoxu5S45fbMZjmTqPPGa2Zuza5/VilsEm13Usb73p/FFuacwzaHhGaboBXvwDI3E4IfoFFnGiUxzhciOcAod0wX8LPzZQMfxLurl6n2+9WK4HpWxkooHzmEkl0gms06yTiuCBkaB8rNtc1pKfvs4QgmAkJg9gJr6OMVz38=,iv:T1O5AlKq3IRW8y4Psdqk6XJNipAWncvhVIZKsiZ6qxM=,tag:vj324H+XUeeu2BaGFI1ysg==,type:str]
            - client_id: synapse
              client_name: Synapse
              redirect_uris:
                - https://matrix.taila659a.ts.net/_matrix/oidc/callback/synapse
              authorization_policy: two_factor
              client_secret: ENC[AES256_GCM,data:1HHJnO5zyKBkMeN3f1tPLiClXks8yWm8pOupHotBatLMZvWj+59oyFowqN/BaxDfezV+bYXs2u+r1I7af59YLb7koeJZrTCWnqYiFbCb0HFkeXgaUtBFkgV3OLXxTYZFCsjUG82CWCU0P5ZWDenoMUKpCQJqKYTk3N4c/b5j3r02cMg=,iv:L9Xaz68xN4UnOWtHxogMl5pvxlxiSW+JmpDvmBXmiok=,tag:DTucPoxV/JlKUAOyNcxOuA==,type:str]
            - client_id: hermes-agent
              client_name: Hermes Agent Dashboard
              redirect_uris:
                - https://automata.i.shikanime.studio/auth/callback
              authorization_policy: two_factor
              public: true
              require_pkce: true
              pkce_challenge_method: S256
            - client_id: vaultwarden
              client_name: Vaultwarden
              redirect_uris:
                - https://vaultwarden.i.shikanime.studio/sso/oidc/callback
              authorization_policy: two_factor
              client_secret: ENC[AES256_GCM,data:GkbF3KHHwAByFI4e0edXUQeWi5/JHl6+dDMkrj0/3l6Cn7HSFoVvVXjjxS/5cWqp2QOt2urhofsPriiDEy8msGWKSzur/n4Jiv7u8YDJEVclD1W5U+akoxX1YYg2isbOqTY3uKMD3PYl/RcBn5o4RFv3qyRw27UqpEPAQoGI5nqUVYM=,iv:0cy82zEJ64QQnHwV4e6BV0zkGZL8hg9T4XsZL00GNpI=,tag:5rvGEU7tGR7JIxWWN9qK9Q==,type:str]
            - client_id: immich
              client_name: Immich
              redirect_uris:
                - https://immich.i.shikanime.studio/auth/login
              authorization_policy: two_factor
              client_secret: ENC[AES256_GCM,data:cd0RO6qkCMliB4NTYXjEu/1ieMmyX4hzI1lS4tMM40+P785cis2HjIB7cPnLA4MB/1DZdGlLyVjNWeMnH2JHsDjyLM9ZPyV8fxxjGKys0K2ykJQGxL+Ua01dQD2zadKveGE3p4PbFkfWo9VmNY09wi0ihCgFJouV7ZzLJE/pJ8oU3oY=,iv:09tagDfqccEC9C/6X0aWkBduvcIBuYakwUiu7wo/H1w=,tag:C7RAkM9FFZOADNSVebkz5A==,type:str]
            - client_id: copyparty
              client_name: Copyparty
              redirect_uris:
                - https://copyparty.i.shikanime.studio/oauth2/callback
              authorization_policy: two_factor
              client_secret: ENC[AES256_GCM,data:LPt57EBhvY0TFIQdibQadvpp9Z+7jCTXYmyAYFr+C749F7zgH2CIscgTaw7Jb7gSz1kAUvgVnLmBmQDgx6SEjYs9UhvSJXP3KwVN4lrxyxFWYNVNrxqr8yWkFrRxEr1agprWgIXRl/zWGeCXfn9yUwdKauxCTMSYZCXVuXZYmdb8n10=,iv:0tSAODjawlWx0HzXo/B7ZM/KjHaYMfLKUBVg4JUilmk=,tag:tL3mKPe0iMiFBX17YCHVNw==,type:str]
regulation:
    max_retries: 3
    find_time: 2m
    ban_time: 15m
totp:
    issuer: Shikanime Studio
    period: 30
    skew: 1
webauthn:
    display_name: Shikanime Studios
access_control:
    default_policy: two_factor
password_policy:
    zxcvbn:
        enabled: true
        min_score: 3
identity_validation:
    reset_password:
        jwt_secret: ENC[AES256_GCM,data:HPQxiE8jaRDCPrwyOjoChJPmoUaIn2e+trC2cLaJCJBWz2ss9VO2/tckA5LFFrE/U6TefjIJdkB7iG2l1mHmTeaC1zG7,iv:PG8IMxtWSJ9Kyf03JizoQbRQpBMSUmUa0CiQDPqXpsc=,tag:SKjGWlOiVuI8RMzxbZb3ng==,type:str]
notifier:
    filesystem:
        filename: /config/notification.txt
server:
    buffers:
        read: 4096
        write: 4096
    disable_healthcheck: true
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMEdjNHZ4Y1R6cm41Wm9E
            MTBxQnFuejQ5UkkzT3BJUnIzcDlBL3RHM3hVClJzdy9xSmgxdlEvZHNuQ1lGOVN3
            bFhDbU9oZW5rR0lDUzRLOTQxV0wzUmsKLS0tIFdSUjhLYkhaVzNUMlMwSFdxaGFD
            dVdlTTdZaVhNbjdOd2F4Nmw1cXNud3MKAAWTePRRRRsNUp2DrCw30LJO2mjLee9p
            Rdqto/ww35TJpYwUV5jQOZ7MtwICeYidTvhRr7fmk8mzYNV0NfLWEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VmtpZWhSY1lGNEZxZ2VI
            SjJnZEFEenRVckI0RStKejQrdDNHZlhaUkY0CmNIV2FYbVV3L3hVL1V0dlluNzVh
            TVpTdTYxNlZVUjdONWtYUG5BamNXaXMKLS0tIFlqTE5rKzdLdDVKdkh1OGJRM3dH
            eGREVkdNcytOMjRZUGtKUno5dVNjSkUKn/S0XDmykRQ4eozMYj7oYsJKpFQCmbv4
            oBhYj7SApI7HTylPNhHZs5quABufV94ID96CpWUrpiNOpsOsciCPTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVEkvMkpVTlBrZk56Zk9w
            c0ZOTDRCaTV2bHd1YlZNSWFzd09qVmloOVZvCmVTYnFXaDF3aXN1c0YyVTFRc1dV
            RjhiclNWL0tDeTJaWkpQVUVFWkhlVDAKLS0tIEp4aTdXaFhRUVl4blNEWXJLbjZp
            dk85eSsvNDA1VGZ4TnpZMU5jbzhHdTQKajqTUfkzLVpiCj5XEZYt8O351bBv9RCo
            lrAO9Qcg31WLjRPoyzQ2wPGVe+UEcnX0+MEzGxKzEs3v29sG5QW7Zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
    encrypted_regex: ^(key|secret|password|encryption_key|jwt_secret|hmac_secret|client_secret)$
    lastmodified: "2026-09-03T10:39:54Z"
    mac: ENC[AES256_GCM,data:7JRqAxWM+QUjqEzVe4jl9gJU6Ody35NAWP/0yv3i6tpV4h/whahRqdFRMo7rltRzWqdKL5s3e0vNdQAdJZYc1B4TFNNwCqBUz6atBAZBH2KHmybO0wpS+Fmqhek0ixtBTe8sS3v2l0zwPODwNpi2HYwI7lPoaTpUxqHN1Jcgk7s=,iv:kwcjbAI4Yf1I2f8Mw0/3KpiIcx3lPsTwcCkY6mctUE8=,tag:o+FqA6QleuSC4R08ewq9mQ==,type:str]
    version: 3.13.3
