resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
  - patch-netpol.yaml
namespace: shikanime
patches:
  - path: patch-cert.yaml
    target:
      name: syncthing-tls
      kind: Certificate
  - path: patch-httproute.yaml
  - path: patch-tcproute.yaml
  - path: patch-udproute.yaml
