resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - netpol.yaml
namespace: shikanime
patches:
  - target:
      name: syncthing
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [syncthing.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: syncthing
            sectionName: https
  - target:
      name: syncthing-redirect
      kind: HTTPRoute
    patch: |
      - op: replace
        path: /spec/hostnames
        value: [syncthing.taila659a.ts.net]
      - op: replace
        path: /spec/parentRefs
        value:
          - name: syncthing
            sectionName: http
