resources:
  - ../../base
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
  - httproute.yaml
  - cert.yaml
secretGenerator:
  - name: discord-webhook
    namespace: flux-system
    envs:
      - discord-webhook/.enc.env
  - name: receiver-token
    namespace: flux-system
    envs:
      - receiver-token/.enc.env
