apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authelia-tls
spec:
  commonName: authelia
  dnsNames:
    - authelia
    - authelia.shikanime
    - authelia.shikanime.svc.cluster.local
  issuerRef:
    name: nishir
    kind: ClusterIssuer
  secretName: authelia-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
