apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shikanime
resources:
  - ../../base
  - backendtlspolicy.yaml
  - cert.yaml
  - gateway.yaml
components:
  - ../../components/tls
patches:
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - authelia.i.shikanime.studio
        - accounts.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: authelia
          sectionName: https
    target:
      name: authelia
      kind: HTTPRoute
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - authelia.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: authelia
          sectionName: http
    target:
      name: authelia-redirect
      kind: HTTPRoute
  - path: patch-pvc.yaml
secretGenerator:
  - name: authelia
    files:
      - authelia/configuration.enc.yaml
