resources:
  - ../../base
  - cert.yaml
  - securitypolicy.yaml
namespace: shikanime
components:
  - ../../components/tls
configurations:
  - namereference.yaml
patches:
  - path: patch-pvc.yaml
  - path: patch-sts.yaml
  - path: patch-httproute.yaml
secretGenerator:
  - name: sonarr
    files:
      - config.xml=sonarr/config.enc.xml
  - name: sonarr-pkcs12-password
    envs:
      - sonarr-pkcs12-password/.enc.env
  - name: sonarr-oidc-client
    envs:
      - sonarr-oidc-client/.enc.env
