apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: deepseek-flash
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: deepseek-flash
  updatePolicy:
    updateMode: InPlaceOrRecreate
