apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload-data
spec:
  resources:
    requests:
      storage: 64Gi
  volumeMode: Filesystem
  volumeName: immich-upload-data
  accessModes:
    - ReadWriteOncePod
