externalDomain: immich.i.shikanime.studio
ffmpeg:
  accel: qsv
  accelDecode: true
notifications:
  smtp:
    enabled: true
    from: nishir.deva@gmail.com
    replyTo: nishir.deva@gmail.com
    transport:
      host: smtp.gmail.com
      ignoreCert: false
      password: ENC[AES256_GCM,data:xgxdopmU3fcMifbcgm6mlw==,iv:5ExecemcEobbxOw9oxb01RdnB7REHy5FR0ziy12sQmY=,tag:OMk6GRkirgwo51+QTx8UkQ==,type:str]
      port: 587
      secure: false
      username: nishir.deva@gmail.com
oauth:
  autoRegister: true
  buttonText: Dex
  clientId: immich
  clientSecret: ENC[AES256_GCM,data:ZCP04Fb900+ygNI5gbwcw7/SqjAX3DPfWAyXPH9hYRU=,iv:lZRtk/2DPjPq7kcl11o+mvQfJjzGktkgDMTxBGCvfTQ=,tag:xHkoNi50ZLP5usKhikafzg==,type:str]
  enabled: true
  issuerUrl: https://accounts.i.shikanime.studio
  profileSigningAlgorithm: none
  scope: openid email profile
  signingAlgorithm: RS256
  storageLabelClaim: preferred_username
  storageQuotaClaim: immich_quota
sops:
  version: 3.13.3
  encrypted_regex: ^(clientSecret|password)$
  lastmodified: "2026-08-11T11:38:26Z"
  mac: ENC[AES256_GCM,data:mKrcGJigPnKAyYfgdNuVbzBQphaqr4CZGbn9+ZY1Ogob5fQoELeNKtSZSbuWMhpk6toEf7ZfKjrtkni/GS4OgB6v2XJHXD5zfBPVS9TeHa7tuZIPC/d4siNzHXzhl337bOvvSNAugnhdtfbigpsOK9XzQWbE19hT/McFJxzYO9M=,iv:qE+GwjAA0lksOwWsDwtcmZJFO7UiN38SDhlMuogPXR0=,tag:O4fCzMlya88RSulkarvryA==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTklCR3ZFRXlyTFRRS05V
        Qk9EbzIrbHhhNlRza0JPRTM3dFlYVC8rc25rClIwVVBvVE8rTTZ6MUJlNUJVY0cw
        WU1EclgzUnRyQmpwN1NWT2NBdGF0STQKLS0tIDA3dWpaK3ArOFdTVG1aMHREeEJ4
        UC9aTlgwZ214SmhBa1Bpc0dWMUVoNFUKEafiU2aERHMx1EmM8+qzELsAxTw5c5oH
        sUAc/rFcSskVgeVjAC2pGr/pOxf+oW7gYX5p2sY4BM7eveqslcrKxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbXFhcW5mRmkzNlZ5OGw1
        cStpWTcwMExNZmhIdDNvU254cndnSEh6aTNFCmsrWHYxRWwwUXhQTkNTUlZZRzcw
        R0txWVdBK1lJTTd5YmNsZThGd29NUDQKLS0tIE1DbG56d2Z6dXdtbVFELzJNc0Fr
        RUdDWmxwOE9iNTdrZW1Na21ZZlAzamsKbWzbVkBWfaSlFOeyZaBzmvuYYeaDUGNj
        jgqJSYttaZem8YwKnuzDmcMPiMLEVHclaGeszZEsegS7fZ/nf90nog==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQb0hhbGswN3dRV0lGdjFT
        SVdJNW9Wanp6dDAwbkhVWUNpQ1VHVDZ4RkhFCkk1TWkzTFhFanJ4U20rVlNtNXpk
        ZTN2QlNRTG9CMzBBOW5HWU9Kc2ZOd2cKLS0tIHJmc2ZDL3loQmdhMlh6K3BnWjJk
        NHlqd2trVGtqcVlVQlFJYjBVYUJ0UUUKMB5zGZ7Ex1BxmmP3bBGRsN5o+I0YM6gx
        hC7yT3fv2Z1UBI0PrxRmY/x5RKrORUZD8SEkKTAtqmN6gNIFz1Do4g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
