externalDomain: immich.i.shikanime.studio
ffmpeg:
  accel: vaapi
  accelDecode: true
notifications:
  smtp:
    enabled: true
    from: nishir.deva@gmail.com
    replyTo: nishir.deva@gmail.com
    transport:
      host: smtp.gmail.com
      ignoreCert: false
      password: ENC[AES256_GCM,data:6WHCXe4vTtr6sWpF+FMFcQ==,iv:4sT6PCdk3eqhBUpxPk0i2M71TrE7bKmQ7ALY2n2hhhs=,tag:DblFC1/H48sCrZYSLZud+Q==,type:str]
      port: 587
      secure: false
      username: nishir.deva@gmail.com
oauth:
  autoRegister: true
  buttonText: Shikanime Studio
  clientId: immich
  clientSecret: ENC[AES256_GCM,data:FilaDxeyt6DxGvkXv4Mvu5kMgIa03s0vxIIN6qwzZEY=,iv:8TkAcMXAoToWBRrcSuWKt53k9B8uuzpduYZDN5azPNk=,tag:JKmiI6dxSxehOzwU0wtx6Q==,type:str]
  enabled: true
  issuerUrl: https://accounts.i.shikanime.studio
  profileSigningAlgorithm: none
  scope: openid email profile
  signingAlgorithm: RS256
  storageLabelClaim: preferred_username
  storageQuotaClaim: immich_quota
sops:
  version: 3.13.3
  encrypted_regex: ^(clientSecret|password)$
  lastmodified: "2026-09-22T22:46:54Z"
  mac: ENC[AES256_GCM,data:LFc4DeVVAGl35cKdDgWzH97ARb1ftXDXzjbOiLmx5nMfjqzCbvj+ZfRLLMqsUvN5CzcygJjVg0zfyriwt4PfaoCRrUGzIfSOkNu7vG1R0p6g6EV6CQrkzsvpJfHhekJR814G3EZfrUY6QK7LRHQv1IMWxwoK8xIl4vcKV8ADlaQ=,iv:79wM34G8IAJAtEIn0UxhDFoK0lH+KBSyFmSGI4hmEUM=,tag:wKAqabR4Saa2yPK/O+sb9A==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0a2JnWk93NHlhM0FsZEJF
        TDEwbjR3MmwzMHk2Sk93eXFvTVk0Q1lLdWlJCktZMnkrcVpCRjh3cm1DTFlrd3Yv
        RUU4cm9ieWtyWVhJemVDeUVuZTFqQ1EKLS0tIDBFZGFPUEN2TnNDWlNJajUzcE5l
        NFB0U25nVzQzOHdJd3VNRk5Ma0l0UFEKy4Y2QleF9UbEYsZ8gGvwybuLqGIdttbz
        cGOvaGW9g7WKYhMWYwrSHb/aGzPYthKL2lfXi8tjkuQjs+mEqnBLOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
