apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qwen-27b
spec:
  ingress: []
  egress: []
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: qwen-27b
      app.kubernetes.io/name: qwen-27b
  policyTypes:
    - Ingress
    - Egress
