resources:
  - ../../base
  - cert.yaml
  - gateway.yaml
patches:
  - patch: "- op: add\n  path: /spec/hostnames\n  value:\n  - mautrix-signal.i.shikanime.studio\n- op: add\n  path: /spec/parentRefs\n  value:\n  - name: signal\n    sectionName: https"
    target:
      name: signal
      kind: HTTPRoute
  - patch: "- op: add\n  path: /spec/hostnames\n  value:\n  - mautrix-signal.i.shikanime.studio\n- op: add\n  path: /spec/parentRefs\n  value:\n  - name: signal\n    sectionName: http"
    target:
      name: signal-redirect
      kind: HTTPRoute
