resources:
  - ../../base
components:
  - ../../components/monitoring
secretGenerator:
  - name: ai-gateway-session-seed
    namespace: flux-system
    envs:
      - ai-gateway-session-seed/.enc.env
configurations:
  - namereference.yaml
