resources:
  - ../../base
  - cert.yaml
  - securitypolicy.yaml
namespace: shikanime
components:
  - ../../components/tls
configurations:
  - namereference.yaml
patches:
  - path: patch-pvc.yaml
  - path: patch-sts.yaml
  - path: patch-httproute.yaml
secretGenerator:
  - name: radarr
    files:
      - config.xml=radarr/config.enc.xml
  - name: radarr-pkcs12-password
    envs:
      - radarr-pkcs12-password/.enc.env
  - name: radarr-oidc-client
    envs:
      - radarr-oidc-client/.enc.env
