resources:
  - ../../base
  - cert.yaml
  - gateway.yaml
  - securitypolicy.yaml
namespace: shikanime
components:
  - ../../components/tls
configurations:
  - namereference.yaml
patches:
  - path: patch-pvc.yaml
  - path: patch-sts.yaml
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - radarr.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: radarr
          sectionName: https
    target:
      name: radarr
      kind: HTTPRoute
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - radarr.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: radarr
          sectionName: http
    target:
      name: radarr-redirect
      kind: HTTPRoute
secretGenerator:
  - name: radarr-env
    envs:
      - radarr-env/.enc.env
  - name: radarr-pkcs12-password
    envs:
      - radarr-pkcs12-password/.enc.env
  - name: radarr-oidc-client
    envs:
      - radarr-oidc-client/.enc.env
