resources:
  - netpol.yaml
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: seerr
    newName: ghcr.io/seerr-team/seerr
    newTag: v3.3.0@sha256:c92d2dc117f62185e7bcb88cd56efd374ea79210eaf433275449e8d5988eb5a8
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "seerr", "tag-regex": "^v(?P<version>\\d+\\.\\d+\\.\\d+)$" }
      ]'
