resources:
  - httproute.yaml
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: seerr
    newName: ghcr.io/seerr-team/seerr
    newTag: v3.5.0@sha256:27602401178d54f1964442287b9f23f67a3fa2252645ee8065839ea1c3f69e45
