---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: whisparr-oidc-client
  namespace: shikanime
spec:
  targetRefs:
    - name: whisparr
      kind: HTTPRoute
      group: gateway.networking.k8s.io
  oidc:
    provider:
      issuer: https://accounts.i.shikanime.studio
    clientID: whisparr
    clientSecret:
      name: whisparr-oidc-client
    redirectURL: https://whisparr.i.shikanime.studio/oauth2/callback
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: whisparr-apikey
  namespace: shikanime
spec:
  targetRefs:
    - name: whisparr-api
      kind: HTTPRoute
      group: gateway.networking.k8s.io
  apiKeyAuth:
    credentialRefs:
      - name: whisparr-env
        kind: Secret
    extractFrom:
      - headers:
          - X-Api-Key
    sanitize: false
