apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: whisparr
  namespace: shikanime
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        pod:
        container:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
      envoyService:
        name: whisparr
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: whisparr-proxy
          tailscale.com/tags: "tag:web"
