apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: vaultwarden
  namespace: shikanime
spec:
  targetRefs:
    - name: vaultwarden
      group: ""
      kind: Service
      sectionName: https
  validation:
    hostname: vaultwarden.shikanime.svc.cluster.local
    caCertificateRefs:
      - name: nishir-ca-certificates.crt
        group: ""
        kind: ConfigMap
