resources:
  - httproute.yaml
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: prowlarr
    newName: lscr.io/linuxserver/prowlarr
    newTag: 2.6.5@sha256:f9151e5bc1025c6d0a630d503210cdcb6bb55a7cc098562609d96a408d838902
