---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flux-receivers
  namespace: envoy-gateway-system
  annotations:
    tailscale.com/funnel: "true"
    tailscale.com/tags: tag:web
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - flux-receivers.taila659a.ts.net
  defaultBackend:
    service:
      name: flux-operator-receivers
      port:
        number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix
  namespace: envoy-gateway-system
  annotations:
    tailscale.com/funnel: "true"
    tailscale.com/tags: tag:web
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - matrix.taila659a.ts.net
  defaultBackend:
    service:
      name: synapse
      port:
        number: 80
