resources:
  - ../nishir
  - ingress.yaml
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: envoy-gateway
      app.kubernetes.io/instance: nishir
      app.kubernetes.io/name: envoy-gateway
      app.kubernetes.io/part-of: nishir-infrastructure
      app.kubernetes.io/version: v1.9.0
