apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: studio-shikanime-i-syncthing-tls
spec:
  commonName: syncthing
  dnsNames:
    - syncthing
    - syncthing.shikanime
    - syncthing.shikanime.svc.cluster.local
  issuerRef:
    name: nishir
    kind: ClusterIssuer
  secretName: studio-shikanime-i-syncthing-tls
  usages:
    - digital signature
    - key encipherment
    - server auth
