apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: slack-redirect
spec:
  hostnames:
    - slack.i.shikanime.studio
  parentRefs:
    - name: slack
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
