resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
  - httproute.yaml
namespace: shikanime
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: communication
      app.kubernetes.io/instance: mautrix-slack
      app.kubernetes.io/name: mautrix-slack
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 0.2607.0
patches:
  - path: patch-netpol.yaml
    target:
      name: mautrix-slack
      version: v1
      kind: NetworkPolicy
secretGenerator:
  - name: mautrix-slack
    files:
      - config.yaml=matrix-slack/config.enc.yaml
      - doublepuppet.yaml=matrix-slack/doublepuppet.enc.yaml
      - registration.yaml=matrix-slack/registration.enc.yaml
    options:
      disableNameSuffixHash: true
