resources:
  - httproute.yaml
  - netpol.yaml
  - sts.yaml
  - svc.yaml
  - tcproute.yaml
  - vpa.yaml
images:
  - name: copyparty
    newName: copyparty/dj
    newTag: 1.20.25@sha256:157a27ffa6d74f1e6d523ebbb8de50f5d85f1dd2956abee696da16e48776e471
