resources:
  - pvc.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
  - netpol.yaml
images:
  - name: copyparty
    newName: copyparty/dj
    newTag: 1.20.18
metadata:
  annotations:
    automata.shikanime.studio/images:
      '[ { "name": "copyparty", "tag-regex": "^(?P<version>.+)$" } ]'
