apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: bazarr
spec:
  gatewayClassName: bazarr
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: bazarr-i-shikanime-studio-tls
            group: ""
            kind: Secret
