resources:
  - ../nishir
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
namespace: shikanime
patches:
  - path: patch-httproute-whatsapp.yaml
    target:
      name: whatsapp
      kind: HTTPRoute
  - path: patch-httproute-whatsapp-redirect.yaml
    target:
      name: whatsapp-redirect
      kind: HTTPRoute
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/component: communication
      app.kubernetes.io/instance: mautrix-whatsapp
      app.kubernetes.io/name: mautrix-whatsapp
      app.kubernetes.io/part-of: nishir-office
      app.kubernetes.io/version: 0.2607.0
secretGenerator:
  - name: mautrix-whatsapp
    files:
      - config.yaml=matrix-whatsapp/config.enc.yaml
      - doublepuppet.yaml=matrix-whatsapp/doublepuppet.enc.yaml
      - registration.yaml=matrix-whatsapp/registration.enc.yaml
    options:
      disableNameSuffixHash: true
