resources:
  - aiservicebackend.yaml
  - backend.yaml
  - backendtrafficpolicy.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: halogen-flash
    newName: ghcr.io/peonist-ai/halogen-flash-server
    newTag: 0.17.2@sha256:0c83ef1093520f0d5b5a00285e59e7ac6b85b1922917fc4a3df95ac5a2638cdd
