resources:
  - aiservicebackend.yaml
  - backend.yaml
  - backendtrafficpolicy.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: halogen-flash
    newName: ghcr.io/peonist-ai/halogen-flash-server
    newTag: 0.16.2@sha256:0c61bf84ac22308a53f5d1ca6b86806702d7039e5ebc51cae4c66621b92fe04a
