resources:
  - aiservicebackend.yaml
  - backend.yaml
  - backendtrafficpolicy.yaml
  - sts.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: halogen-flash
    newName: ghcr.io/peonist-ai/halogen-flash-server
    newTag: 0.17.5@sha256:df161433d825e901d91811fe28561bc3ef830a552bbb59c1aaf58f8fd4e9bc1d
