---
apiVersion: v1
kind: Service
metadata:
  name: halogen-flash
spec:
  selector:
    app.kubernetes.io/instance: halogen-flash
    app.kubernetes.io/name: halogen-flash
  ports:
    - name: http
      appProtocol: http
      port: 8731
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: halogen-flash-headless
  namespace: shikanime
  labels:
    app.kubernetes.io/component: inference
    app.kubernetes.io/instance: halogen-flash
    app.kubernetes.io/name: halogen-flash
    app.kubernetes.io/part-of: nishir-inference
    app.kubernetes.io/version: "0.15.0"
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: halogen-flash
    app.kubernetes.io/name: halogen-flash
  ports:
    - name: http
      port: 8731
      targetPort: http
