apiVersion: v1
kind: Service
metadata:
  name: halogen-flash
spec:
  selector:
    app.kubernetes.io/instance: halogen-flash
    app.kubernetes.io/name: halogen-flash
  ports:
    - name: http
      appProtocol: http
      port: 8731
      protocol: TCP
      targetPort: http
