resources:
  - ../../base
namespace: shikanime
patches:
secretGenerator:
  - name: honcho-postgres
    type: basic-auth
    envs:
      - honcho-postgres/.enc.env
    options:
      disableNameSuffixHash: true
