apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: trust-manager
  namespace: cert-manager-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trust-manager
  updatePolicy:
    updateMode: Auto
