name: Commands
permissions:
  contents: read
"on":
  issue_comment:
    types:
      - created
jobs:
  backport:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '.backport')
    runs-on: ubuntu-slim
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
          permission-workflows: write
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-studio/actions/nix/setup@68a5b49e707bb499fe73cd1b7dddb95fd4a66716
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-studio/actions/command/backport@68a5b49e707bb499fe73cd1b7dddb95fd4a66716
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          sign-commits: true
  close:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '.close')
    runs-on: ubuntu-slim
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-studio/actions/nix/setup@68a5b49e707bb499fe73cd1b7dddb95fd4a66716
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-studio/actions/command/close@68a5b49e707bb499fe73cd1b7dddb95fd4a66716
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
          username: yorha-automata
  land:
    if: github.event.issue.pull_request != null && (contains(github.event.comment.body, '.land') || contains(github.event.comment.body, '.force-land'))
    runs-on: ubuntu-slim
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-administration: read
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
          permission-workflows: write
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-studio/actions/nix/setup@68a5b49e707bb499fe73cd1b7dddb95fd4a66716
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-studio/actions/command/land@68a5b49e707bb499fe73cd1b7dddb95fd4a66716
        with:
          email: automata@shikanime.studio
          fullname: Automata
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          sign-commits: true
          username: yorha-automata
  rebase:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '.rebase')
    runs-on: ubuntu-slim
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
          permission-workflows: write
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-studio/actions/nix/setup@68a5b49e707bb499fe73cd1b7dddb95fd4a66716
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-studio/actions/command/rebase@68a5b49e707bb499fe73cd1b7dddb95fd4a66716
        with:
          email: automata@shikanime.studio
          fullname: Automata
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          sign-commits: true
          username: yorha-automata
  run:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '.run')
    runs-on: ubuntu-slim
    steps:
      - id: createGithubAppToken
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        with:
          app-id: ${{ vars.OPERATOR_APP_ID }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write
          private-key: ${{ secrets.OPERATOR_PRIVATE_KEY }}
      - uses: shikanime-studio/actions/nix/setup@68a5b49e707bb499fe73cd1b7dddb95fd4a66716
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
      - uses: shikanime-studio/actions/command/run@68a5b49e707bb499fe73cd1b7dddb95fd4a66716
        with:
          github-token: ${{ steps.createGithubAppToken.outputs.token }}
