apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        name: longhorn
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: longhorn
          tailscale.com/tags: "tag:web"
