appservice:
  id: discord
  address: http://mautrix-discord.shikanime.svc.cluster.local:29334
  as_token: ENC[AES256_GCM,data:glmC53Wnc5gIJIb/DarVNn/xfWR3o2nI67NHwBkOdoHmGYwGIzbga/3vpniUmIMT1C09MDy1UxKHH3S42ujBZQ==,iv:GO4oi13CVWhUQnORKRTs1lCc04UCcX7tI3F5w/fha+8=,tag:mtNn/1OY4UQhckXoienihQ==,type:str]
  async_transactions: false
  ephemeral_events: true
  hostname: 0.0.0.0
  hs_token: ENC[AES256_GCM,data:TUDgsSpvyXnh2ufYKR8caObcpnq9GDumTPXEqlyQlPEmBEvd7X6D6uvpMaFB+caNvzY3Pat5VLWaZKy/WkGoJw==,iv:x+8MFxlUV0pjXsxMkmtaa8/WqVpOgO4A/nLEGrcXitc=,tag:8K406Na/Z7X6skpfS6WunA==,type:str]
  port: 29334
  bot:
    avatar: mxc://maunium.net/nIdEykemnwdisvHbpxflpDlC
    displayname: Discord bridge bot
    username: discordbot
  database:
    type: sqlite3-fk-wal
    max_conn_idle_time: null
    max_conn_lifetime: null
    max_idle_conns: 2
    max_open_conns: 20
    uri: file:/data/discord.db?_txlock=immediate
bridge:
  animated_sticker:
    args:
      fps: 25
      height: 320
      width: 320
    target: webp
  autojoin_thread_on_open: true
  avatar_proxy_key: ENC[AES256_GCM,data:hFxubuBC8W8mAeba7C/dDr9GjIluuJsY7dA+yclpqd8=,iv:7VKr5A4hEK3Bea88Hg9UhI7PRE+QtRIMb3wqe2yRdhI=,tag:4pPLbuPQ5ScLX5raXbSn7A==,type:str]
  backfill:
    forward_limits:
      initial:
        channel: 50
        dm: 50
        thread: 50
      missed:
        channel: 500
        dm: 500
        thread: 500
    max_guild_members: -1
  cache_media: unencrypted
  channel_name_template: "{{if or (eq .Type 3) (eq .Type 4)}}{{.Name}}{{else}}#{{.Name}}{{end}}"
  command_prefix: "!discord"
  custom_emoji_reactions: true
  delete_guild_on_leave: true
  delete_portal_on_channel_delete: false
  delivery_receipts: false
  direct_media:
    allow_proxy: true
    enabled: false
    server_key: ENC[AES256_GCM,data:xlOwE4R96yCYXVnPqm6FxPK83QXvbyz154bNGj56SwLx6ZKi1jmYnJPLJxfIRQbm+OF8OD7X4aY6xg==,iv:UF0/i8osKjNm1w5H5p6w2jz2qy/YZA525vT/COGsV3g=,tag:DQ6DAB5343ZiHnhUaLzn6g==,type:str]
    server_name: matrix-discord-media.taila659a.ts.net
    well_known_response: null
  displayname_template: "{{if .Webhook}}Webhook{{else}}{{or .GlobalName .Username}}{{if .Bot}} (bot){{end}}{{end}}"
  double_puppet_allow_discovery: false
  double_puppet_server_map:
    matrix.i.shikanime.studio: https://matrix.i.shikanime.studio
  embed_fields_as_tables: true
  enable_webhook_avatars: false
  encryption:
    allow: true
    allow_key_sharing: false
    appservice: false
    default: true
    delete_keys:
      delete_fully_used_on_decrypt: true
      delete_on_device_delete: true
      delete_outbound_on_ack: false
      delete_outdated_inbound: true
      delete_prev_on_new_session: true
      dont_store_outbound: true
      periodically_delete_expired: true
      ratchet_on_decrypt: true
    msc4190: false
    plaintext_mentions: false
    require: false
    rotation:
      disable_device_change_key_rotation: false
      enable_custom: false
      messages: 100
      milliseconds: 6.048e+08
    self_sign: true
    verification_levels:
      receive: cross-signed-tofu
      send: cross-signed-tofu
      share: cross-signed-tofu
  federate_rooms: true
  guild_name_template: "{{.Name}}"
  login_shared_secret_map:
    matrix.i.shikanime.studio: ENC[AES256_GCM,data:nlaSzsBzX4PPlz4GLKE6Ltw3Y7FeP/pPP8IJTx7g2zJREQcdjLYlaUDoHiVde1RLS7+yKNgVB9+osX5kRCxHKw==,iv:ozTWa2/1ZRix5jJ7133QdIOYpSRP9ZZARiC8+lrQ0BM=,tag:ZPO0XYfkQByVxnrox27w2w==,type:str]
  management_room_text:
    additional_help: ""
    welcome: Hello, I'm a Discord bridge bot.
    welcome_connected: Use `help` for help.
    welcome_unconnected: Use `help` for help or `login` to log in.
  message_error_notices: true
  message_status_events: false
  mute_channels_on_create: false
  permissions:
    "*": relay
    "@root:matrix.i.shikanime.studio": admin
    matrix.i.shikanime.studio: user
  portal_message_buffer: 128
  prefix_webhook_messages: true
  private_chat_portal_meta: default
  provisioning:
    debug_endpoints: false
    prefix: /_matrix/provision
    shared_secret: ENC[AES256_GCM,data:p3/NJcVuNre27IDKtP/HtXkPVDr9qVlcwu0al2VZaLu4p/NK99mWB0jf47NwJzAfh4cigPXCF9vCS0oHG5x5NA==,iv:T6Br8UAjDHVnyd9uiyN5tsKwzBO+dK2DYwe91edX2U8=,tag:ynaTx8Q0vynwUAtjAODadQ==,type:str]
  proxy: null
  public_address: https://matrix-discord.taila659a.ts.net
  resend_bridge_info: false
  restricted_rooms: true
  startup_private_channel_create_limit: 5
  sync_direct_chat_list: false
  use_discord_cdn_upload: true
  username_template: discord_{{.}}
homeserver:
  address: https://synapse.shikanime.svc.cluster.local:8448
  async_media: false
  domain: matrix.i.shikanime.studio
  message_send_checkpoint_endpoint: null
  ping_interval_seconds: 0
  software: standard
  status_endpoint: null
  websocket: false
logging:
  min_level: debug
  writers:
    - type: stdout
      format: pretty-colored
    - type: file
      compress: true
      filename: ./logs/mautrix-discord.log
      format: json
      max_backups: 10
      max_size: 100
sops:
  version: 3.13.3
  encrypted_regex: ^(avatar_proxy_key|as_token|hs_token|pickle_key|server_key|shared_secret|signing_key|login_shared_secret_map|secrets)$
  lastmodified: "2026-08-31T12:15:06Z"
  mac: ENC[AES256_GCM,data:gCl/Cl72OXBuU0P8+9TgFUtx0cTc9e52eAxP34I5gW435gxKa+qnsVGErO9nqVv/BarWyA3WsfaF6xHBTHtpb0Xiu1A3bqf5sAWnUHInWy6HBmxK6m9V0gj0UP2O/iaEKBgOO+1OfEJqbfUn41CyWjLy7e+aiGwGfdjqt9Tc0m8=,iv:+gJNwYrIXBoUxjpJJW3Ow6+BgpQIveloJtmd7wuQyug=,tag:70wb2sylzAooAGToQEkLAw==,type:str]
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUkQrRmtYaWJsMERDR1pn
        V0J2WjV3WkxreEova1Y5ZFZmb3RuTzdYN1N3ClJGalAxUTBZOUNtdlJmTGpmZFpk
        UGNqRHVmM3A3ZDFRSCtpWEFJRjNpd1UKLS0tIHZyRmFkU3dRajBsTm4zaE1OYnU2
        bTN1SXZLTGxFc3J4OFNZSmxpUDJXMFUK520mrO//JAB8yWMzmZwVKA5C+Co2Aqd1
        +b4vxkC8jU0xkGt7MqYGkPnxAqCdKigOM7mG/jtizQvaPwMB2lRE+A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17q5ljstyzkvqtejwfnyf5jvqduars2yauw7vtgu5fcf54tm2jf0sspvt3c
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNUNaeFZiZ1dvVUVrZ1VF
        NUlnU3ZtVHFSSXM0Vll3QzV2ZlRSRGhTN1c4CkR2ZEJsVUpMbmlZY1FEcUtIcHVJ
        d0ljdGVHc0s5Vm1TNk5WT3BkV0RNWDgKLS0tIGhNMTExOU95QlVoTEMyT2ZwdG5D
        UDRCT3pTZVhnNEd4Q3ZjNGlNWmIyeUUKIMqI17QJHuatECyh6NwGBxdrjkXei09B
        dqEANfVC+QBwOHCfyCayQ+VJBu+kvgBGxNl7f2eK5BDo816bf+fUHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1x9v4ps90txy9mk4392uya93tyzx40te4dvns4chg5s6q8mfy03ns74jpay
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQVlzRHBaQzlsYlJjcjdr
        Tkx5UmRMVjJaUi8yWmhnWi9odUNJUXpFTlZzCnNOYzNsZFdiKzlaNTFhVjFZRUd0
        cVJISHR0Qmo0VXRHL2FYbkgrc2MyLzQKLS0tICtSV01NeXN4OEdLZE1hOGpVV00v
        YUdNalB4WnJJRlZBSmJLeU9ERkNmekEKkRsZu/Xjdh4B3Ssg1Xwq4GoG/TIe1xVP
        RtmW2AA2NSTTZZafT9pMOraetZP0yYX6f0GdrgehYrBJyKpkSbBBCA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f4yuh4j3gqafjduusfpxz3na9xtwth9s6gznq043mfex0zglp5jqkkdm64
