resources:
  - ../../base
  - cert.yaml
  - gateway.yaml
  - httproute.yaml
  - vmalertmanagerconfig.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - grafana.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: grafana
          sectionName: https
    target:
      name: grafana
      kind: HTTPRoute
      namespace: monitoring-system
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - grafana.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: grafana
          sectionName: http
    target:
      name: grafana-redirect
      kind: HTTPRoute
      namespace: monitoring-system
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - telemetry.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: grafana
          sectionName: https-telemetry
    target:
      name: telemetry
      kind: HTTPRoute
      namespace: monitoring-system
  - patch: |-
      - op: add
        path: /spec/hostnames
        value:
        - telemetry.i.shikanime.studio
      - op: add
        path: /spec/parentRefs
        value:
        - name: grafana
          sectionName: http
    target:
      name: telemetry-redirect
      kind: HTTPRoute
      namespace: monitoring-system
  - path: patch-hr.yaml
  - path: patch-hr-vmalertmanager.yaml
components:
  - ../../components/authelia
  - ../../components/forgejo
  - ../../components/honcho
  - ../../components/mautrix
secretGenerator:
  - name: discord-webhook
    namespace: monitoring-system
    envs:
      - discord-webhook/.enc.env
