resources:
  - deploy.yaml
  - httproute.yaml
  - netpol.yaml
  - svc.yaml
  - vpa.yaml
images:
  - name: honcho
    newName: ghcr.io/plastic-labs/honcho
    newTag: v3.3.0@sha256:22ef9951be7868b1af455bd2b7d35ba0dbdae75f48f1c0d2ca9d00fbd3f43559
